// Code generated by ogen, DO NOT EDIT.

package openapi

import (
	"net/http"
	"net/url"
	"strings"

	"github.com/ogen-go/ogen/uri"
)

var (
	rn8AllowedHeaders = map[string]string{
		"DELETE": "Idempotency-Key",
	}
	rn9AllowedHeaders = map[string]string{
		"POST": "Content-Type,Idempotency-Key",
	}
	rn11AllowedHeaders = map[string]string{
		"POST": "Content-Type,Idempotency-Key",
	}
	rn14AllowedHeaders = map[string]string{
		"POST": "Content-Type,Idempotency-Key",
	}
	rn2AllowedHeaders = map[string]string{
		"DELETE": "Idempotency-Key",
	}
	rn5AllowedHeaders = map[string]string{
		"POST": "Idempotency-Key",
	}
	rn3AllowedHeaders = map[string]string{
		"POST": "Content-Type,Idempotency-Key",
	}
	rn27AllowedHeaders = map[string]string{
		"GET": "Last-Event-Id",
	}
	rn15AllowedHeaders = map[string]string{
		"POST": "Content-Type,Idempotency-Key",
	}
	rn22AllowedHeaders = map[string]string{
		"POST": "Content-Type,Idempotency-Key",
	}
	rn12AllowedHeaders = map[string]string{
		"POST": "Content-Type,Idempotency-Key",
	}
	rn24AllowedHeaders = map[string]string{
		"POST": "Content-Type,Idempotency-Key",
	}
	rn26AllowedHeaders = map[string]string{
		"POST": "Content-Type,Idempotency-Key",
	}
	rn13AllowedHeaders = map[string]string{
		"POST": "Content-Type,Idempotency-Key",
	}
)

func (s *Server) cutPrefix(path string) (string, bool) {
	prefix := s.cfg.Prefix
	if prefix == "" {
		return path, true
	}
	if !strings.HasPrefix(path, prefix) {
		// Prefix doesn't match.
		return "", false
	}
	// Cut prefix from the path.
	return strings.TrimPrefix(path, prefix), true
}

// ServeHTTP serves http request as defined by OpenAPI v3 specification,
// calling handler that matches the path or returning not found error.
func (s *Server) ServeHTTP(w http.ResponseWriter, r *http.Request) {
	elem := r.URL.Path
	elemIsEscaped := false
	if rawPath := r.URL.RawPath; rawPath != "" {
		if normalized, ok := uri.NormalizeEscapedPath(rawPath); ok {
			elem = normalized
			elemIsEscaped = strings.ContainsRune(elem, '%')
		}
	}

	elem, ok := s.cutPrefix(elem)
	if !ok || len(elem) == 0 {
		s.notFound(w, r)
		return
	}
	args := [2]string{}

	// Static code generated router with unwrapped path search.
	switch {
	default:
		if len(elem) == 0 {
			break
		}
		switch elem[0] {
		case '/': // Prefix: "/v1/"

			if l := len("/v1/"); len(elem) >= l && elem[0:l] == "/v1/" {
				elem = elem[l:]
			} else {
				break
			}

			if len(elem) == 0 {
				break
			}
			switch elem[0] {
			case 'i': // Prefix: "imports/"

				if l := len("imports/"); len(elem) >= l && elem[0:l] == "imports/" {
					elem = elem[l:]
				} else {
					break
				}

				// Param: "import_id"
				// Leaf parameter, slashes are prohibited
				idx := strings.IndexByte(elem, '/')
				if idx >= 0 {
					break
				}
				args[0] = elem
				elem = ""

				if len(elem) == 0 {
					// Leaf node.
					switch r.Method {
					case "GET":
						s.handleGetImportRequest([1]string{
							args[0],
						}, elemIsEscaped, w, r)
					default:
						s.notAllowed(w, r, notAllowedParams{
							allowedMethods: "GET",
							allowedHeaders: nil,
							acceptPost:     "",
							acceptPatch:    "",
						})
					}

					return
				}

			case 'm': // Prefix: "materializations/"

				if l := len("materializations/"); len(elem) >= l && elem[0:l] == "materializations/" {
					elem = elem[l:]
				} else {
					break
				}

				// Param: "materialization_id"
				// Match until "/"
				idx := strings.IndexByte(elem, '/')
				if idx < 0 {
					idx = len(elem)
				}
				args[0] = elem[:idx]
				elem = elem[idx:]

				if len(elem) == 0 {
					switch r.Method {
					case "DELETE":
						s.handleReleaseMaterializationRequest([1]string{
							args[0],
						}, elemIsEscaped, w, r)
					case "GET":
						s.handleGetMaterializationRequest([1]string{
							args[0],
						}, elemIsEscaped, w, r)
					default:
						s.notAllowed(w, r, notAllowedParams{
							allowedMethods: "DELETE,GET",
							allowedHeaders: rn8AllowedHeaders,
							acceptPost:     "",
							acceptPatch:    "",
						})
					}

					return
				}
				switch elem[0] {
				case '/': // Prefix: "/c"

					if l := len("/c"); len(elem) >= l && elem[0:l] == "/c" {
						elem = elem[l:]
					} else {
						break
					}

					if len(elem) == 0 {
						break
					}
					switch elem[0] {
					case 'h': // Prefix: "heckpoint"

						if l := len("heckpoint"); len(elem) >= l && elem[0:l] == "heckpoint" {
							elem = elem[l:]
						} else {
							break
						}

						if len(elem) == 0 {
							// Leaf node.
							switch r.Method {
							case "POST":
								s.handleCheckpointMaterializationRequest([1]string{
									args[0],
								}, elemIsEscaped, w, r)
							default:
								s.notAllowed(w, r, notAllowedParams{
									allowedMethods: "POST",
									allowedHeaders: rn9AllowedHeaders,
									acceptPost:     "application/json",
									acceptPatch:    "",
								})
							}

							return
						}

					case 'o': // Prefix: "ommit"

						if l := len("ommit"); len(elem) >= l && elem[0:l] == "ommit" {
							elem = elem[l:]
						} else {
							break
						}

						if len(elem) == 0 {
							// Leaf node.
							switch r.Method {
							case "POST":
								s.handleCommitMaterializationRequest([1]string{
									args[0],
								}, elemIsEscaped, w, r)
							default:
								s.notAllowed(w, r, notAllowedParams{
									allowedMethods: "POST",
									allowedHeaders: rn11AllowedHeaders,
									acceptPost:     "application/json",
									acceptPatch:    "",
								})
							}

							return
						}

					}

				}

			case 'w': // Prefix: "workspaces"

				if l := len("workspaces"); len(elem) >= l && elem[0:l] == "workspaces" {
					elem = elem[l:]
				} else {
					break
				}

				if len(elem) == 0 {
					switch r.Method {
					case "GET":
						s.handleListWorkspacesRequest([0]string{}, elemIsEscaped, w, r)
					case "POST":
						s.handleCreateWorkspaceRequest([0]string{}, elemIsEscaped, w, r)
					default:
						s.notAllowed(w, r, notAllowedParams{
							allowedMethods: "GET,POST",
							allowedHeaders: rn14AllowedHeaders,
							acceptPost:     "application/json",
							acceptPatch:    "",
						})
					}

					return
				}
				switch elem[0] {
				case '/': // Prefix: "/"

					if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
						elem = elem[l:]
					} else {
						break
					}

					// Param: "workspace_id"
					// Match until "/"
					idx := strings.IndexByte(elem, '/')
					if idx < 0 {
						idx = len(elem)
					}
					args[0] = elem[:idx]
					elem = elem[idx:]

					if len(elem) == 0 {
						switch r.Method {
						case "DELETE":
							s.handleDeleteWorkspaceRequest([1]string{
								args[0],
							}, elemIsEscaped, w, r)
						case "GET":
							s.handleGetWorkspaceRequest([1]string{
								args[0],
							}, elemIsEscaped, w, r)
						default:
							s.notAllowed(w, r, notAllowedParams{
								allowedMethods: "DELETE,GET",
								allowedHeaders: rn2AllowedHeaders,
								acceptPost:     "",
								acceptPatch:    "",
							})
						}

						return
					}
					switch elem[0] {
					case '/': // Prefix: "/"

						if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
							elem = elem[l:]
						} else {
							break
						}

						if len(elem) == 0 {
							break
						}
						switch elem[0] {
						case 'a': // Prefix: "archive"

							if l := len("archive"); len(elem) >= l && elem[0:l] == "archive" {
								elem = elem[l:]
							} else {
								break
							}

							if len(elem) == 0 {
								// Leaf node.
								switch r.Method {
								case "POST":
									s.handleArchiveWorkspaceRequest([1]string{
										args[0],
									}, elemIsEscaped, w, r)
								default:
									s.notAllowed(w, r, notAllowedParams{
										allowedMethods: "POST",
										allowedHeaders: rn5AllowedHeaders,
										acceptPost:     "",
										acceptPatch:    "",
									})
								}

								return
							}

						case 'c': // Prefix: "components"

							if l := len("components"); len(elem) >= l && elem[0:l] == "components" {
								elem = elem[l:]
							} else {
								break
							}

							if len(elem) == 0 {
								switch r.Method {
								case "GET":
									s.handleListComponentsRequest([1]string{
										args[0],
									}, elemIsEscaped, w, r)
								case "POST":
									s.handleAddComponentRequest([1]string{
										args[0],
									}, elemIsEscaped, w, r)
								default:
									s.notAllowed(w, r, notAllowedParams{
										allowedMethods: "GET,POST",
										allowedHeaders: rn3AllowedHeaders,
										acceptPost:     "application/json",
										acceptPatch:    "",
									})
								}

								return
							}
							switch elem[0] {
							case '/': // Prefix: "/"

								if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
									elem = elem[l:]
								} else {
									break
								}

								// Param: "component_id"
								// Leaf parameter, slashes are prohibited
								idx := strings.IndexByte(elem, '/')
								if idx >= 0 {
									break
								}
								args[1] = elem
								elem = ""

								if len(elem) == 0 {
									// Leaf node.
									switch r.Method {
									case "GET":
										s.handleGetComponentRequest([2]string{
											args[0],
											args[1],
										}, elemIsEscaped, w, r)
									default:
										s.notAllowed(w, r, notAllowedParams{
											allowedMethods: "GET",
											allowedHeaders: nil,
											acceptPost:     "",
											acceptPatch:    "",
										})
									}

									return
								}

							}

						case 'e': // Prefix: "events"

							if l := len("events"); len(elem) >= l && elem[0:l] == "events" {
								elem = elem[l:]
							} else {
								break
							}

							if len(elem) == 0 {
								// Leaf node.
								switch r.Method {
								case "GET":
									s.handleStreamWorkspaceEventsRequest([1]string{
										args[0],
									}, elemIsEscaped, w, r)
								default:
									s.notAllowed(w, r, notAllowedParams{
										allowedMethods: "GET",
										allowedHeaders: rn27AllowedHeaders,
										acceptPost:     "",
										acceptPatch:    "",
									})
								}

								return
							}

						case 'f': // Prefix: "forks"

							if l := len("forks"); len(elem) >= l && elem[0:l] == "forks" {
								elem = elem[l:]
							} else {
								break
							}

							if len(elem) == 0 {
								// Leaf node.
								switch r.Method {
								case "POST":
									s.handleForkWorkspaceRequest([1]string{
										args[0],
									}, elemIsEscaped, w, r)
								default:
									s.notAllowed(w, r, notAllowedParams{
										allowedMethods: "POST",
										allowedHeaders: rn15AllowedHeaders,
										acceptPost:     "application/json",
										acceptPatch:    "",
									})
								}

								return
							}

						case 'g': // Prefix: "generations"

							if l := len("generations"); len(elem) >= l && elem[0:l] == "generations" {
								elem = elem[l:]
							} else {
								break
							}

							if len(elem) == 0 {
								switch r.Method {
								case "GET":
									s.handleListGenerationsRequest([1]string{
										args[0],
									}, elemIsEscaped, w, r)
								default:
									s.notAllowed(w, r, notAllowedParams{
										allowedMethods: "GET",
										allowedHeaders: nil,
										acceptPost:     "",
										acceptPatch:    "",
									})
								}

								return
							}
							switch elem[0] {
							case '/': // Prefix: "/"

								if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
									elem = elem[l:]
								} else {
									break
								}

								// Param: "generation"
								// Leaf parameter, slashes are prohibited
								idx := strings.IndexByte(elem, '/')
								if idx >= 0 {
									break
								}
								args[1] = elem
								elem = ""

								if len(elem) == 0 {
									// Leaf node.
									switch r.Method {
									case "GET":
										s.handleGetGenerationRequest([2]string{
											args[0],
											args[1],
										}, elemIsEscaped, w, r)
									default:
										s.notAllowed(w, r, notAllowedParams{
											allowedMethods: "GET",
											allowedHeaders: nil,
											acceptPost:     "",
											acceptPatch:    "",
										})
									}

									return
								}

							}

						case 'i': // Prefix: "imports"

							if l := len("imports"); len(elem) >= l && elem[0:l] == "imports" {
								elem = elem[l:]
							} else {
								break
							}

							if len(elem) == 0 {
								// Leaf node.
								switch r.Method {
								case "POST":
									s.handleImportSourceRequest([1]string{
										args[0],
									}, elemIsEscaped, w, r)
								default:
									s.notAllowed(w, r, notAllowedParams{
										allowedMethods: "POST",
										allowedHeaders: rn22AllowedHeaders,
										acceptPost:     "application/json",
										acceptPatch:    "",
									})
								}

								return
							}

						case 'm': // Prefix: "materializations"

							if l := len("materializations"); len(elem) >= l && elem[0:l] == "materializations" {
								elem = elem[l:]
							} else {
								break
							}

							if len(elem) == 0 {
								// Leaf node.
								switch r.Method {
								case "POST":
									s.handleCreateMaterializationRequest([1]string{
										args[0],
									}, elemIsEscaped, w, r)
								default:
									s.notAllowed(w, r, notAllowedParams{
										allowedMethods: "POST",
										allowedHeaders: rn12AllowedHeaders,
										acceptPost:     "application/json",
										acceptPatch:    "",
									})
								}

								return
							}

						case 'r': // Prefix: "re"

							if l := len("re"); len(elem) >= l && elem[0:l] == "re" {
								elem = elem[l:]
							} else {
								break
							}

							if len(elem) == 0 {
								break
							}
							switch elem[0] {
							case 'f': // Prefix: "freshes"

								if l := len("freshes"); len(elem) >= l && elem[0:l] == "freshes" {
									elem = elem[l:]
								} else {
									break
								}

								if len(elem) == 0 {
									// Leaf node.
									switch r.Method {
									case "POST":
										s.handleRefreshSourcesRequest([1]string{
											args[0],
										}, elemIsEscaped, w, r)
									default:
										s.notAllowed(w, r, notAllowedParams{
											allowedMethods: "POST",
											allowedHeaders: rn24AllowedHeaders,
											acceptPost:     "application/json",
											acceptPatch:    "",
										})
									}

									return
								}

							case 's': // Prefix: "store"

								if l := len("store"); len(elem) >= l && elem[0:l] == "store" {
									elem = elem[l:]
								} else {
									break
								}

								if len(elem) == 0 {
									// Leaf node.
									switch r.Method {
									case "POST":
										s.handleRestoreWorkspaceRequest([1]string{
											args[0],
										}, elemIsEscaped, w, r)
									default:
										s.notAllowed(w, r, notAllowedParams{
											allowedMethods: "POST",
											allowedHeaders: rn26AllowedHeaders,
											acceptPost:     "application/json",
											acceptPatch:    "",
										})
									}

									return
								}

							}

						case 's': // Prefix: "snapshots"

							if l := len("snapshots"); len(elem) >= l && elem[0:l] == "snapshots" {
								elem = elem[l:]
							} else {
								break
							}

							if len(elem) == 0 {
								// Leaf node.
								switch r.Method {
								case "GET":
									s.handleListPortableSnapshotsRequest([1]string{
										args[0],
									}, elemIsEscaped, w, r)
								case "POST":
									s.handleCreatePortableSnapshotRequest([1]string{
										args[0],
									}, elemIsEscaped, w, r)
								default:
									s.notAllowed(w, r, notAllowedParams{
										allowedMethods: "GET,POST",
										allowedHeaders: rn13AllowedHeaders,
										acceptPost:     "application/json",
										acceptPatch:    "",
									})
								}

								return
							}

						}

					}

				}

			}

		}
	}
	s.notFound(w, r)
}

// Route is route object.
type Route struct {
	name           string
	summary        string
	operationID    string
	operationGroup string
	pathPattern    string
	count          int
	args           [2]string
}

// Name returns ogen operation name.
//
// It is guaranteed to be unique and not empty.
func (r Route) Name() string {
	return r.name
}

// Summary returns OpenAPI summary.
func (r Route) Summary() string {
	return r.summary
}

// OperationID returns OpenAPI operationId.
func (r Route) OperationID() string {
	return r.operationID
}

// OperationGroup returns the x-ogen-operation-group value.
func (r Route) OperationGroup() string {
	return r.operationGroup
}

// PathPattern returns OpenAPI path.
func (r Route) PathPattern() string {
	return r.pathPattern
}

// Args returns parsed arguments.
func (r Route) Args() []string {
	return r.args[:r.count]
}

// FindRoute finds Route for given method and path.
//
// Note: this method does not unescape path or handle reserved characters in path properly. Use FindPath instead.
func (s *Server) FindRoute(method, path string) (Route, bool) {
	return s.FindPath(method, &url.URL{Path: path})
}

// FindPath finds Route for given method and URL.
func (s *Server) FindPath(method string, u *url.URL) (r Route, _ bool) {
	var (
		elem = u.Path
		args = r.args
	)
	if rawPath := u.RawPath; rawPath != "" {
		if normalized, ok := uri.NormalizeEscapedPath(rawPath); ok {
			elem = normalized
		}
		defer func() {
			for i, arg := range r.args[:r.count] {
				if unescaped, err := url.PathUnescape(arg); err == nil {
					r.args[i] = unescaped
				}
			}
		}()
	}

	elem, ok := s.cutPrefix(elem)
	if !ok {
		return r, false
	}

	// Static code generated router with unwrapped path search.
	switch {
	default:
		if len(elem) == 0 {
			break
		}
		switch elem[0] {
		case '/': // Prefix: "/v1/"

			if l := len("/v1/"); len(elem) >= l && elem[0:l] == "/v1/" {
				elem = elem[l:]
			} else {
				break
			}

			if len(elem) == 0 {
				break
			}
			switch elem[0] {
			case 'i': // Prefix: "imports/"

				if l := len("imports/"); len(elem) >= l && elem[0:l] == "imports/" {
					elem = elem[l:]
				} else {
					break
				}

				// Param: "import_id"
				// Leaf parameter, slashes are prohibited
				idx := strings.IndexByte(elem, '/')
				if idx >= 0 {
					break
				}
				args[0] = elem
				elem = ""

				if len(elem) == 0 {
					// Leaf node.
					switch method {
					case "GET":
						r.name = GetImportOperation
						r.summary = ""
						r.operationID = "getImport"
						r.operationGroup = ""
						r.pathPattern = "/v1/imports/{import_id}"
						r.args = args
						r.count = 1
						return r, true
					default:
						return
					}
				}

			case 'm': // Prefix: "materializations/"

				if l := len("materializations/"); len(elem) >= l && elem[0:l] == "materializations/" {
					elem = elem[l:]
				} else {
					break
				}

				// Param: "materialization_id"
				// Match until "/"
				idx := strings.IndexByte(elem, '/')
				if idx < 0 {
					idx = len(elem)
				}
				args[0] = elem[:idx]
				elem = elem[idx:]

				if len(elem) == 0 {
					switch method {
					case "DELETE":
						r.name = ReleaseMaterializationOperation
						r.summary = ""
						r.operationID = "releaseMaterialization"
						r.operationGroup = ""
						r.pathPattern = "/v1/materializations/{materialization_id}"
						r.args = args
						r.count = 1
						return r, true
					case "GET":
						r.name = GetMaterializationOperation
						r.summary = ""
						r.operationID = "getMaterialization"
						r.operationGroup = ""
						r.pathPattern = "/v1/materializations/{materialization_id}"
						r.args = args
						r.count = 1
						return r, true
					default:
						return
					}
				}
				switch elem[0] {
				case '/': // Prefix: "/c"

					if l := len("/c"); len(elem) >= l && elem[0:l] == "/c" {
						elem = elem[l:]
					} else {
						break
					}

					if len(elem) == 0 {
						break
					}
					switch elem[0] {
					case 'h': // Prefix: "heckpoint"

						if l := len("heckpoint"); len(elem) >= l && elem[0:l] == "heckpoint" {
							elem = elem[l:]
						} else {
							break
						}

						if len(elem) == 0 {
							// Leaf node.
							switch method {
							case "POST":
								r.name = CheckpointMaterializationOperation
								r.summary = ""
								r.operationID = "checkpointMaterialization"
								r.operationGroup = ""
								r.pathPattern = "/v1/materializations/{materialization_id}/checkpoint"
								r.args = args
								r.count = 1
								return r, true
							default:
								return
							}
						}

					case 'o': // Prefix: "ommit"

						if l := len("ommit"); len(elem) >= l && elem[0:l] == "ommit" {
							elem = elem[l:]
						} else {
							break
						}

						if len(elem) == 0 {
							// Leaf node.
							switch method {
							case "POST":
								r.name = CommitMaterializationOperation
								r.summary = ""
								r.operationID = "commitMaterialization"
								r.operationGroup = ""
								r.pathPattern = "/v1/materializations/{materialization_id}/commit"
								r.args = args
								r.count = 1
								return r, true
							default:
								return
							}
						}

					}

				}

			case 'w': // Prefix: "workspaces"

				if l := len("workspaces"); len(elem) >= l && elem[0:l] == "workspaces" {
					elem = elem[l:]
				} else {
					break
				}

				if len(elem) == 0 {
					switch method {
					case "GET":
						r.name = ListWorkspacesOperation
						r.summary = ""
						r.operationID = "listWorkspaces"
						r.operationGroup = ""
						r.pathPattern = "/v1/workspaces"
						r.args = args
						r.count = 0
						return r, true
					case "POST":
						r.name = CreateWorkspaceOperation
						r.summary = ""
						r.operationID = "createWorkspace"
						r.operationGroup = ""
						r.pathPattern = "/v1/workspaces"
						r.args = args
						r.count = 0
						return r, true
					default:
						return
					}
				}
				switch elem[0] {
				case '/': // Prefix: "/"

					if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
						elem = elem[l:]
					} else {
						break
					}

					// Param: "workspace_id"
					// Match until "/"
					idx := strings.IndexByte(elem, '/')
					if idx < 0 {
						idx = len(elem)
					}
					args[0] = elem[:idx]
					elem = elem[idx:]

					if len(elem) == 0 {
						switch method {
						case "DELETE":
							r.name = DeleteWorkspaceOperation
							r.summary = ""
							r.operationID = "deleteWorkspace"
							r.operationGroup = ""
							r.pathPattern = "/v1/workspaces/{workspace_id}"
							r.args = args
							r.count = 1
							return r, true
						case "GET":
							r.name = GetWorkspaceOperation
							r.summary = ""
							r.operationID = "getWorkspace"
							r.operationGroup = ""
							r.pathPattern = "/v1/workspaces/{workspace_id}"
							r.args = args
							r.count = 1
							return r, true
						default:
							return
						}
					}
					switch elem[0] {
					case '/': // Prefix: "/"

						if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
							elem = elem[l:]
						} else {
							break
						}

						if len(elem) == 0 {
							break
						}
						switch elem[0] {
						case 'a': // Prefix: "archive"

							if l := len("archive"); len(elem) >= l && elem[0:l] == "archive" {
								elem = elem[l:]
							} else {
								break
							}

							if len(elem) == 0 {
								// Leaf node.
								switch method {
								case "POST":
									r.name = ArchiveWorkspaceOperation
									r.summary = ""
									r.operationID = "archiveWorkspace"
									r.operationGroup = ""
									r.pathPattern = "/v1/workspaces/{workspace_id}/archive"
									r.args = args
									r.count = 1
									return r, true
								default:
									return
								}
							}

						case 'c': // Prefix: "components"

							if l := len("components"); len(elem) >= l && elem[0:l] == "components" {
								elem = elem[l:]
							} else {
								break
							}

							if len(elem) == 0 {
								switch method {
								case "GET":
									r.name = ListComponentsOperation
									r.summary = ""
									r.operationID = "listComponents"
									r.operationGroup = ""
									r.pathPattern = "/v1/workspaces/{workspace_id}/components"
									r.args = args
									r.count = 1
									return r, true
								case "POST":
									r.name = AddComponentOperation
									r.summary = ""
									r.operationID = "addComponent"
									r.operationGroup = ""
									r.pathPattern = "/v1/workspaces/{workspace_id}/components"
									r.args = args
									r.count = 1
									return r, true
								default:
									return
								}
							}
							switch elem[0] {
							case '/': // Prefix: "/"

								if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
									elem = elem[l:]
								} else {
									break
								}

								// Param: "component_id"
								// Leaf parameter, slashes are prohibited
								idx := strings.IndexByte(elem, '/')
								if idx >= 0 {
									break
								}
								args[1] = elem
								elem = ""

								if len(elem) == 0 {
									// Leaf node.
									switch method {
									case "GET":
										r.name = GetComponentOperation
										r.summary = ""
										r.operationID = "getComponent"
										r.operationGroup = ""
										r.pathPattern = "/v1/workspaces/{workspace_id}/components/{component_id}"
										r.args = args
										r.count = 2
										return r, true
									default:
										return
									}
								}

							}

						case 'e': // Prefix: "events"

							if l := len("events"); len(elem) >= l && elem[0:l] == "events" {
								elem = elem[l:]
							} else {
								break
							}

							if len(elem) == 0 {
								// Leaf node.
								switch method {
								case "GET":
									r.name = StreamWorkspaceEventsOperation
									r.summary = ""
									r.operationID = "streamWorkspaceEvents"
									r.operationGroup = ""
									r.pathPattern = "/v1/workspaces/{workspace_id}/events"
									r.args = args
									r.count = 1
									return r, true
								default:
									return
								}
							}

						case 'f': // Prefix: "forks"

							if l := len("forks"); len(elem) >= l && elem[0:l] == "forks" {
								elem = elem[l:]
							} else {
								break
							}

							if len(elem) == 0 {
								// Leaf node.
								switch method {
								case "POST":
									r.name = ForkWorkspaceOperation
									r.summary = ""
									r.operationID = "forkWorkspace"
									r.operationGroup = ""
									r.pathPattern = "/v1/workspaces/{workspace_id}/forks"
									r.args = args
									r.count = 1
									return r, true
								default:
									return
								}
							}

						case 'g': // Prefix: "generations"

							if l := len("generations"); len(elem) >= l && elem[0:l] == "generations" {
								elem = elem[l:]
							} else {
								break
							}

							if len(elem) == 0 {
								switch method {
								case "GET":
									r.name = ListGenerationsOperation
									r.summary = ""
									r.operationID = "listGenerations"
									r.operationGroup = ""
									r.pathPattern = "/v1/workspaces/{workspace_id}/generations"
									r.args = args
									r.count = 1
									return r, true
								default:
									return
								}
							}
							switch elem[0] {
							case '/': // Prefix: "/"

								if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
									elem = elem[l:]
								} else {
									break
								}

								// Param: "generation"
								// Leaf parameter, slashes are prohibited
								idx := strings.IndexByte(elem, '/')
								if idx >= 0 {
									break
								}
								args[1] = elem
								elem = ""

								if len(elem) == 0 {
									// Leaf node.
									switch method {
									case "GET":
										r.name = GetGenerationOperation
										r.summary = ""
										r.operationID = "getGeneration"
										r.operationGroup = ""
										r.pathPattern = "/v1/workspaces/{workspace_id}/generations/{generation}"
										r.args = args
										r.count = 2
										return r, true
									default:
										return
									}
								}

							}

						case 'i': // Prefix: "imports"

							if l := len("imports"); len(elem) >= l && elem[0:l] == "imports" {
								elem = elem[l:]
							} else {
								break
							}

							if len(elem) == 0 {
								// Leaf node.
								switch method {
								case "POST":
									r.name = ImportSourceOperation
									r.summary = ""
									r.operationID = "importSource"
									r.operationGroup = ""
									r.pathPattern = "/v1/workspaces/{workspace_id}/imports"
									r.args = args
									r.count = 1
									return r, true
								default:
									return
								}
							}

						case 'm': // Prefix: "materializations"

							if l := len("materializations"); len(elem) >= l && elem[0:l] == "materializations" {
								elem = elem[l:]
							} else {
								break
							}

							if len(elem) == 0 {
								// Leaf node.
								switch method {
								case "POST":
									r.name = CreateMaterializationOperation
									r.summary = ""
									r.operationID = "createMaterialization"
									r.operationGroup = ""
									r.pathPattern = "/v1/workspaces/{workspace_id}/materializations"
									r.args = args
									r.count = 1
									return r, true
								default:
									return
								}
							}

						case 'r': // Prefix: "re"

							if l := len("re"); len(elem) >= l && elem[0:l] == "re" {
								elem = elem[l:]
							} else {
								break
							}

							if len(elem) == 0 {
								break
							}
							switch elem[0] {
							case 'f': // Prefix: "freshes"

								if l := len("freshes"); len(elem) >= l && elem[0:l] == "freshes" {
									elem = elem[l:]
								} else {
									break
								}

								if len(elem) == 0 {
									// Leaf node.
									switch method {
									case "POST":
										r.name = RefreshSourcesOperation
										r.summary = ""
										r.operationID = "refreshSources"
										r.operationGroup = ""
										r.pathPattern = "/v1/workspaces/{workspace_id}/refreshes"
										r.args = args
										r.count = 1
										return r, true
									default:
										return
									}
								}

							case 's': // Prefix: "store"

								if l := len("store"); len(elem) >= l && elem[0:l] == "store" {
									elem = elem[l:]
								} else {
									break
								}

								if len(elem) == 0 {
									// Leaf node.
									switch method {
									case "POST":
										r.name = RestoreWorkspaceOperation
										r.summary = ""
										r.operationID = "restoreWorkspace"
										r.operationGroup = ""
										r.pathPattern = "/v1/workspaces/{workspace_id}/restore"
										r.args = args
										r.count = 1
										return r, true
									default:
										return
									}
								}

							}

						case 's': // Prefix: "snapshots"

							if l := len("snapshots"); len(elem) >= l && elem[0:l] == "snapshots" {
								elem = elem[l:]
							} else {
								break
							}

							if len(elem) == 0 {
								// Leaf node.
								switch method {
								case "GET":
									r.name = ListPortableSnapshotsOperation
									r.summary = ""
									r.operationID = "listPortableSnapshots"
									r.operationGroup = ""
									r.pathPattern = "/v1/workspaces/{workspace_id}/snapshots"
									r.args = args
									r.count = 1
									return r, true
								case "POST":
									r.name = CreatePortableSnapshotOperation
									r.summary = ""
									r.operationID = "createPortableSnapshot"
									r.operationGroup = ""
									r.pathPattern = "/v1/workspaces/{workspace_id}/snapshots"
									r.args = args
									r.count = 1
									return r, true
								default:
									return
								}
							}

						}

					}

				}

			}

		}
	}
	return r, false
}
