// Code generated by ogen, DO NOT EDIT.

package openapi

import (
	"fmt"
	"hash/fnv"
)

// Hash computes a hash value for CreateMaterializationComponentAccessItem using FNV-1a.
// Equal objects must produce equal hashes.
func (a CreateMaterializationComponentAccessItem) Hash() uint64 {
	h := fnv.New64a()

	// Hash primitive field: ComponentId
	h.Write([]byte(fmt.Sprintf("%v", a.ComponentId)))
	// Hash primitive field: Mode
	h.Write([]byte(fmt.Sprintf("%v", a.Mode)))
	return h.Sum64()
}
