// Code generated by ogen, DO NOT EDIT.

package openapi

// setDefaults set default value of fields.
func (s *ForkWorkspaceReq) setDefaults() {
	{
		val := bool(false)
		s.IncludeProfileReferences.SetTo(val)
	}
}
