// Code generated by ogen, DO NOT EDIT.

package openapi

import (
	"fmt"
	"io"
	"net/url"
	"time"

	"github.com/go-faster/errors"
	"github.com/go-faster/jx"
	"github.com/google/uuid"
)

func (s *ProblemStatusCode) Error() string {
	return fmt.Sprintf("code %d: %+v", s.StatusCode, s.Response)
}

type Classification jx.Raw

// Merged schema.
// Ref: #/components/schemas/CommitRequest
type CommitRequest struct {
	LeaseId                UUID   `json:"leaseId"`
	FencingToken           int    `json:"fencingToken"`
	ExpectedHeadGeneration int    `json:"expectedHeadGeneration"`
	Durability             jx.Raw `json:"durability"`
}

// GetLeaseId returns the value of LeaseId.
func (s *CommitRequest) GetLeaseId() UUID {
	return s.LeaseId
}

// GetFencingToken returns the value of FencingToken.
func (s *CommitRequest) GetFencingToken() int {
	return s.FencingToken
}

// GetExpectedHeadGeneration returns the value of ExpectedHeadGeneration.
func (s *CommitRequest) GetExpectedHeadGeneration() int {
	return s.ExpectedHeadGeneration
}

// GetDurability returns the value of Durability.
func (s *CommitRequest) GetDurability() jx.Raw {
	return s.Durability
}

// SetLeaseId sets the value of LeaseId.
func (s *CommitRequest) SetLeaseId(val UUID) {
	s.LeaseId = val
}

// SetFencingToken sets the value of FencingToken.
func (s *CommitRequest) SetFencingToken(val int) {
	s.FencingToken = val
}

// SetExpectedHeadGeneration sets the value of ExpectedHeadGeneration.
func (s *CommitRequest) SetExpectedHeadGeneration(val int) {
	s.ExpectedHeadGeneration = val
}

// SetDurability sets the value of Durability.
func (s *CommitRequest) SetDurability(val jx.Raw) {
	s.Durability = val
}

// Merged schema.
// Ref: #/components/schemas/Component
type Component struct {
	Name           Name             `json:"name"`
	Kind           jx.Raw           `json:"kind"`
	Path           string           `json:"path"`
	Source         OptSourceBinding `json:"source"`
	ID             UUID             `json:"id"`
	Classification Classification   `json:"classification"`
	Taints         []string         `json:"taints"`
}

// GetName returns the value of Name.
func (s *Component) GetName() Name {
	return s.Name
}

// GetKind returns the value of Kind.
func (s *Component) GetKind() jx.Raw {
	return s.Kind
}

// GetPath returns the value of Path.
func (s *Component) GetPath() string {
	return s.Path
}

// GetSource returns the value of Source.
func (s *Component) GetSource() OptSourceBinding {
	return s.Source
}

// GetID returns the value of ID.
func (s *Component) GetID() UUID {
	return s.ID
}

// GetClassification returns the value of Classification.
func (s *Component) GetClassification() Classification {
	return s.Classification
}

// GetTaints returns the value of Taints.
func (s *Component) GetTaints() []string {
	return s.Taints
}

// SetName sets the value of Name.
func (s *Component) SetName(val Name) {
	s.Name = val
}

// SetKind sets the value of Kind.
func (s *Component) SetKind(val jx.Raw) {
	s.Kind = val
}

// SetPath sets the value of Path.
func (s *Component) SetPath(val string) {
	s.Path = val
}

// SetSource sets the value of Source.
func (s *Component) SetSource(val OptSourceBinding) {
	s.Source = val
}

// SetID sets the value of ID.
func (s *Component) SetID(val UUID) {
	s.ID = val
}

// SetClassification sets the value of Classification.
func (s *Component) SetClassification(val Classification) {
	s.Classification = val
}

// SetTaints sets the value of Taints.
func (s *Component) SetTaints(val []string) {
	s.Taints = val
}

// Ref: #/components/schemas/ComponentInput
type ComponentInput struct {
	Name   Name             `json:"name"`
	Kind   jx.Raw           `json:"kind"`
	Path   string           `json:"path"`
	Source OptSourceBinding `json:"source"`
}

// GetName returns the value of Name.
func (s *ComponentInput) GetName() Name {
	return s.Name
}

// GetKind returns the value of Kind.
func (s *ComponentInput) GetKind() jx.Raw {
	return s.Kind
}

// GetPath returns the value of Path.
func (s *ComponentInput) GetPath() string {
	return s.Path
}

// GetSource returns the value of Source.
func (s *ComponentInput) GetSource() OptSourceBinding {
	return s.Source
}

// SetName sets the value of Name.
func (s *ComponentInput) SetName(val Name) {
	s.Name = val
}

// SetKind sets the value of Kind.
func (s *ComponentInput) SetKind(val jx.Raw) {
	s.Kind = val
}

// SetPath sets the value of Path.
func (s *ComponentInput) SetPath(val string) {
	s.Path = val
}

// SetSource sets the value of Source.
func (s *ComponentInput) SetSource(val OptSourceBinding) {
	s.Source = val
}

// Ref: #/components/schemas/CreateMaterialization
type CreateMaterialization struct {
	Generation      int                                        `json:"generation"`
	ComponentAccess []CreateMaterializationComponentAccessItem `json:"componentAccess"`
	Mode            jx.Raw                                     `json:"mode"`
	Target          TargetContext                              `json:"target"`
	// Opaque AG grant reference; never a downstream credential.
	ExecutionGrant string `json:"executionGrant"`
}

// GetGeneration returns the value of Generation.
func (s *CreateMaterialization) GetGeneration() int {
	return s.Generation
}

// GetComponentAccess returns the value of ComponentAccess.
func (s *CreateMaterialization) GetComponentAccess() []CreateMaterializationComponentAccessItem {
	return s.ComponentAccess
}

// GetMode returns the value of Mode.
func (s *CreateMaterialization) GetMode() jx.Raw {
	return s.Mode
}

// GetTarget returns the value of Target.
func (s *CreateMaterialization) GetTarget() TargetContext {
	return s.Target
}

// GetExecutionGrant returns the value of ExecutionGrant.
func (s *CreateMaterialization) GetExecutionGrant() string {
	return s.ExecutionGrant
}

// SetGeneration sets the value of Generation.
func (s *CreateMaterialization) SetGeneration(val int) {
	s.Generation = val
}

// SetComponentAccess sets the value of ComponentAccess.
func (s *CreateMaterialization) SetComponentAccess(val []CreateMaterializationComponentAccessItem) {
	s.ComponentAccess = val
}

// SetMode sets the value of Mode.
func (s *CreateMaterialization) SetMode(val jx.Raw) {
	s.Mode = val
}

// SetTarget sets the value of Target.
func (s *CreateMaterialization) SetTarget(val TargetContext) {
	s.Target = val
}

// SetExecutionGrant sets the value of ExecutionGrant.
func (s *CreateMaterialization) SetExecutionGrant(val string) {
	s.ExecutionGrant = val
}

type CreateMaterializationComponentAccessItem struct {
	ComponentId UUID                                         `json:"componentId"`
	Mode        CreateMaterializationComponentAccessItemMode `json:"mode"`
}

// GetComponentId returns the value of ComponentId.
func (s *CreateMaterializationComponentAccessItem) GetComponentId() UUID {
	return s.ComponentId
}

// GetMode returns the value of Mode.
func (s *CreateMaterializationComponentAccessItem) GetMode() CreateMaterializationComponentAccessItemMode {
	return s.Mode
}

// SetComponentId sets the value of ComponentId.
func (s *CreateMaterializationComponentAccessItem) SetComponentId(val UUID) {
	s.ComponentId = val
}

// SetMode sets the value of Mode.
func (s *CreateMaterializationComponentAccessItem) SetMode(val CreateMaterializationComponentAccessItemMode) {
	s.Mode = val
}

type CreateMaterializationComponentAccessItemMode string

const (
	CreateMaterializationComponentAccessItemModeReadOnly  CreateMaterializationComponentAccessItemMode = "read-only"
	CreateMaterializationComponentAccessItemModeReadWrite CreateMaterializationComponentAccessItemMode = "read-write"
)

// AllValues returns all CreateMaterializationComponentAccessItemMode values.
func (CreateMaterializationComponentAccessItemMode) AllValues() []CreateMaterializationComponentAccessItemMode {
	return []CreateMaterializationComponentAccessItemMode{
		CreateMaterializationComponentAccessItemModeReadOnly,
		CreateMaterializationComponentAccessItemModeReadWrite,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s CreateMaterializationComponentAccessItemMode) MarshalText() ([]byte, error) {
	switch s {
	case CreateMaterializationComponentAccessItemModeReadOnly:
		return []byte(s), nil
	case CreateMaterializationComponentAccessItemModeReadWrite:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *CreateMaterializationComponentAccessItemMode) UnmarshalText(data []byte) error {
	switch CreateMaterializationComponentAccessItemMode(data) {
	case CreateMaterializationComponentAccessItemModeReadOnly:
		*s = CreateMaterializationComponentAccessItemModeReadOnly
		return nil
	case CreateMaterializationComponentAccessItemModeReadWrite:
		*s = CreateMaterializationComponentAccessItemModeReadWrite
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

type CreatePortableSnapshotReq struct {
	Generation int `json:"generation"`
}

// GetGeneration returns the value of Generation.
func (s *CreatePortableSnapshotReq) GetGeneration() int {
	return s.Generation
}

// SetGeneration sets the value of Generation.
func (s *CreatePortableSnapshotReq) SetGeneration(val int) {
	s.Generation = val
}

// Ref: #/components/schemas/CreateWorkspace
type CreateWorkspace struct {
	Name           Name           `json:"name"`
	Owner          Owner          `json:"owner"`
	Classification Classification `json:"classification"`
	Residency      []string       `json:"residency"`
}

// GetName returns the value of Name.
func (s *CreateWorkspace) GetName() Name {
	return s.Name
}

// GetOwner returns the value of Owner.
func (s *CreateWorkspace) GetOwner() Owner {
	return s.Owner
}

// GetClassification returns the value of Classification.
func (s *CreateWorkspace) GetClassification() Classification {
	return s.Classification
}

// GetResidency returns the value of Residency.
func (s *CreateWorkspace) GetResidency() []string {
	return s.Residency
}

// SetName sets the value of Name.
func (s *CreateWorkspace) SetName(val Name) {
	s.Name = val
}

// SetOwner sets the value of Owner.
func (s *CreateWorkspace) SetOwner(val Owner) {
	s.Owner = val
}

// SetClassification sets the value of Classification.
func (s *CreateWorkspace) SetClassification(val Classification) {
	s.Classification = val
}

// SetResidency sets the value of Residency.
func (s *CreateWorkspace) SetResidency(val []string) {
	s.Residency = val
}

// Ref: #/components/schemas/FencedRequest
type FencedRequest struct {
	LeaseId      UUID `json:"leaseId"`
	FencingToken int  `json:"fencingToken"`
}

// GetLeaseId returns the value of LeaseId.
func (s *FencedRequest) GetLeaseId() UUID {
	return s.LeaseId
}

// GetFencingToken returns the value of FencingToken.
func (s *FencedRequest) GetFencingToken() int {
	return s.FencingToken
}

// SetLeaseId sets the value of LeaseId.
func (s *FencedRequest) SetLeaseId(val UUID) {
	s.LeaseId = val
}

// SetFencingToken sets the value of FencingToken.
func (s *FencedRequest) SetFencingToken(val int) {
	s.FencingToken = val
}

type ForkWorkspaceReq struct {
	Generation               int     `json:"generation"`
	Name                     Name    `json:"name"`
	IncludeProfileReferences OptBool `json:"includeProfileReferences"`
}

// GetGeneration returns the value of Generation.
func (s *ForkWorkspaceReq) GetGeneration() int {
	return s.Generation
}

// GetName returns the value of Name.
func (s *ForkWorkspaceReq) GetName() Name {
	return s.Name
}

// GetIncludeProfileReferences returns the value of IncludeProfileReferences.
func (s *ForkWorkspaceReq) GetIncludeProfileReferences() OptBool {
	return s.IncludeProfileReferences
}

// SetGeneration sets the value of Generation.
func (s *ForkWorkspaceReq) SetGeneration(val int) {
	s.Generation = val
}

// SetName sets the value of Name.
func (s *ForkWorkspaceReq) SetName(val Name) {
	s.Name = val
}

// SetIncludeProfileReferences sets the value of IncludeProfileReferences.
func (s *ForkWorkspaceReq) SetIncludeProfileReferences(val OptBool) {
	s.IncludeProfileReferences = val
}

// Ref: #/components/schemas/Generation
type Generation struct {
	WorkspaceId      UUID      `json:"workspaceId"`
	Number           int       `json:"number"`
	State            string    `json:"state"`
	ParentGeneration OptInt    `json:"parentGeneration"`
	ManifestDigest   string    `json:"manifestDigest"`
	Durability       jx.Raw    `json:"durability"`
	CreatedAt        time.Time `json:"createdAt"`
}

// GetWorkspaceId returns the value of WorkspaceId.
func (s *Generation) GetWorkspaceId() UUID {
	return s.WorkspaceId
}

// GetNumber returns the value of Number.
func (s *Generation) GetNumber() int {
	return s.Number
}

// GetState returns the value of State.
func (s *Generation) GetState() string {
	return s.State
}

// GetParentGeneration returns the value of ParentGeneration.
func (s *Generation) GetParentGeneration() OptInt {
	return s.ParentGeneration
}

// GetManifestDigest returns the value of ManifestDigest.
func (s *Generation) GetManifestDigest() string {
	return s.ManifestDigest
}

// GetDurability returns the value of Durability.
func (s *Generation) GetDurability() jx.Raw {
	return s.Durability
}

// GetCreatedAt returns the value of CreatedAt.
func (s *Generation) GetCreatedAt() time.Time {
	return s.CreatedAt
}

// SetWorkspaceId sets the value of WorkspaceId.
func (s *Generation) SetWorkspaceId(val UUID) {
	s.WorkspaceId = val
}

// SetNumber sets the value of Number.
func (s *Generation) SetNumber(val int) {
	s.Number = val
}

// SetState sets the value of State.
func (s *Generation) SetState(val string) {
	s.State = val
}

// SetParentGeneration sets the value of ParentGeneration.
func (s *Generation) SetParentGeneration(val OptInt) {
	s.ParentGeneration = val
}

// SetManifestDigest sets the value of ManifestDigest.
func (s *Generation) SetManifestDigest(val string) {
	s.ManifestDigest = val
}

// SetDurability sets the value of Durability.
func (s *Generation) SetDurability(val jx.Raw) {
	s.Durability = val
}

// SetCreatedAt sets the value of CreatedAt.
func (s *Generation) SetCreatedAt(val time.Time) {
	s.CreatedAt = val
}

// Ref: #/components/schemas/ImportRequest
type ImportRequest struct {
	Component              ComponentInput `json:"component"`
	Source                 SourceBinding  `json:"source"`
	ExpectedHeadGeneration int            `json:"expectedHeadGeneration"`
}

// GetComponent returns the value of Component.
func (s *ImportRequest) GetComponent() ComponentInput {
	return s.Component
}

// GetSource returns the value of Source.
func (s *ImportRequest) GetSource() SourceBinding {
	return s.Source
}

// GetExpectedHeadGeneration returns the value of ExpectedHeadGeneration.
func (s *ImportRequest) GetExpectedHeadGeneration() int {
	return s.ExpectedHeadGeneration
}

// SetComponent sets the value of Component.
func (s *ImportRequest) SetComponent(val ComponentInput) {
	s.Component = val
}

// SetSource sets the value of Source.
func (s *ImportRequest) SetSource(val SourceBinding) {
	s.Source = val
}

// SetExpectedHeadGeneration sets the value of ExpectedHeadGeneration.
func (s *ImportRequest) SetExpectedHeadGeneration(val int) {
	s.ExpectedHeadGeneration = val
}

// Ref: #/components/schemas/Materialization
type Materialization struct {
	ID           UUID          `json:"id"`
	WorkspaceId  UUID          `json:"workspaceId"`
	Generation   int           `json:"generation"`
	Mode         jx.Raw        `json:"mode"`
	State        jx.Raw        `json:"state"`
	Target       TargetContext `json:"target"`
	FencingToken OptInt        `json:"fencingToken"`
	ExpiresAt    OptDateTime   `json:"expiresAt"`
	// Opaque non-authorizing provider handle.
	Handle OptString `json:"handle"`
}

// GetID returns the value of ID.
func (s *Materialization) GetID() UUID {
	return s.ID
}

// GetWorkspaceId returns the value of WorkspaceId.
func (s *Materialization) GetWorkspaceId() UUID {
	return s.WorkspaceId
}

// GetGeneration returns the value of Generation.
func (s *Materialization) GetGeneration() int {
	return s.Generation
}

// GetMode returns the value of Mode.
func (s *Materialization) GetMode() jx.Raw {
	return s.Mode
}

// GetState returns the value of State.
func (s *Materialization) GetState() jx.Raw {
	return s.State
}

// GetTarget returns the value of Target.
func (s *Materialization) GetTarget() TargetContext {
	return s.Target
}

// GetFencingToken returns the value of FencingToken.
func (s *Materialization) GetFencingToken() OptInt {
	return s.FencingToken
}

// GetExpiresAt returns the value of ExpiresAt.
func (s *Materialization) GetExpiresAt() OptDateTime {
	return s.ExpiresAt
}

// GetHandle returns the value of Handle.
func (s *Materialization) GetHandle() OptString {
	return s.Handle
}

// SetID sets the value of ID.
func (s *Materialization) SetID(val UUID) {
	s.ID = val
}

// SetWorkspaceId sets the value of WorkspaceId.
func (s *Materialization) SetWorkspaceId(val UUID) {
	s.WorkspaceId = val
}

// SetGeneration sets the value of Generation.
func (s *Materialization) SetGeneration(val int) {
	s.Generation = val
}

// SetMode sets the value of Mode.
func (s *Materialization) SetMode(val jx.Raw) {
	s.Mode = val
}

// SetState sets the value of State.
func (s *Materialization) SetState(val jx.Raw) {
	s.State = val
}

// SetTarget sets the value of Target.
func (s *Materialization) SetTarget(val TargetContext) {
	s.Target = val
}

// SetFencingToken sets the value of FencingToken.
func (s *Materialization) SetFencingToken(val OptInt) {
	s.FencingToken = val
}

// SetExpiresAt sets the value of ExpiresAt.
func (s *Materialization) SetExpiresAt(val OptDateTime) {
	s.ExpiresAt = val
}

// SetHandle sets the value of Handle.
func (s *Materialization) SetHandle(val OptString) {
	s.Handle = val
}

type Name string

// Ref: #/components/schemas/Operation
type Operation struct {
	ID         UUID        `json:"id"`
	State      jx.Raw      `json:"state"`
	ResourceId OptUUID     `json:"resourceId"`
	CreatedAt  OptDateTime `json:"createdAt"`
}

// GetID returns the value of ID.
func (s *Operation) GetID() UUID {
	return s.ID
}

// GetState returns the value of State.
func (s *Operation) GetState() jx.Raw {
	return s.State
}

// GetResourceId returns the value of ResourceId.
func (s *Operation) GetResourceId() OptUUID {
	return s.ResourceId
}

// GetCreatedAt returns the value of CreatedAt.
func (s *Operation) GetCreatedAt() OptDateTime {
	return s.CreatedAt
}

// SetID sets the value of ID.
func (s *Operation) SetID(val UUID) {
	s.ID = val
}

// SetState sets the value of State.
func (s *Operation) SetState(val jx.Raw) {
	s.State = val
}

// SetResourceId sets the value of ResourceId.
func (s *Operation) SetResourceId(val OptUUID) {
	s.ResourceId = val
}

// SetCreatedAt sets the value of CreatedAt.
func (s *Operation) SetCreatedAt(val OptDateTime) {
	s.CreatedAt = val
}

// NewOptBool returns new OptBool with value set to v.
func NewOptBool(v bool) OptBool {
	return OptBool{
		Value: v,
		Set:   true,
	}
}

// OptBool is optional bool.
type OptBool struct {
	Value bool
	Set   bool
}

// IsSet returns true if OptBool was set.
func (o OptBool) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptBool) Reset() {
	var v bool
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptBool) SetTo(v bool) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptBool) Get() (v bool, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptBool) Or(d bool) bool {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptDateTime returns new OptDateTime with value set to v.
func NewOptDateTime(v time.Time) OptDateTime {
	return OptDateTime{
		Value: v,
		Set:   true,
	}
}

// OptDateTime is optional time.Time.
type OptDateTime struct {
	Value time.Time
	Set   bool
}

// IsSet returns true if OptDateTime was set.
func (o OptDateTime) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptDateTime) Reset() {
	var v time.Time
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptDateTime) SetTo(v time.Time) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptDateTime) Get() (v time.Time, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptDateTime) Or(d time.Time) time.Time {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptInt returns new OptInt with value set to v.
func NewOptInt(v int) OptInt {
	return OptInt{
		Value: v,
		Set:   true,
	}
}

// OptInt is optional int.
type OptInt struct {
	Value int
	Set   bool
}

// IsSet returns true if OptInt was set.
func (o OptInt) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptInt) Reset() {
	var v int
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptInt) SetTo(v int) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptInt) Get() (v int, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptInt) Or(d int) int {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptNilString returns new OptNilString with value set to v.
func NewOptNilString(v string) OptNilString {
	return OptNilString{
		Value: v,
		Set:   true,
	}
}

// OptNilString is optional nullable string.
type OptNilString struct {
	Value string
	Set   bool
	Null  bool
}

// IsSet returns true if OptNilString was set.
func (o OptNilString) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptNilString) Reset() {
	var v string
	o.Value = v
	o.Set = false
	o.Null = false
}

// SetTo sets value to v.
func (o *OptNilString) SetTo(v string) {
	o.Set = true
	o.Null = false
	o.Value = v
}

// IsNull returns true if value is Null.
func (o OptNilString) IsNull() bool { return o.Null }

// SetToNull sets value to null.
func (o *OptNilString) SetToNull() {
	o.Set = true
	o.Null = true
	var v string
	o.Value = v
}

// IsEmpty returns true if the field was omitted from the payload (not Set and not Null).
func (o OptNilString) IsEmpty() bool {
	return !o.Set && !o.Null
}

// Get returns value and boolean that denotes whether value was set.
func (o OptNilString) Get() (v string, ok bool) {
	if o.Null {
		return v, false
	}
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptNilString) Or(d string) string {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptSourceBinding returns new OptSourceBinding with value set to v.
func NewOptSourceBinding(v SourceBinding) OptSourceBinding {
	return OptSourceBinding{
		Value: v,
		Set:   true,
	}
}

// OptSourceBinding is optional SourceBinding.
type OptSourceBinding struct {
	Value SourceBinding
	Set   bool
}

// IsSet returns true if OptSourceBinding was set.
func (o OptSourceBinding) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptSourceBinding) Reset() {
	var v SourceBinding
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptSourceBinding) SetTo(v SourceBinding) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptSourceBinding) Get() (v SourceBinding, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptSourceBinding) Or(d SourceBinding) SourceBinding {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptString returns new OptString with value set to v.
func NewOptString(v string) OptString {
	return OptString{
		Value: v,
		Set:   true,
	}
}

// OptString is optional string.
type OptString struct {
	Value string
	Set   bool
}

// IsSet returns true if OptString was set.
func (o OptString) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptString) Reset() {
	var v string
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptString) SetTo(v string) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptString) Get() (v string, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptString) Or(d string) string {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptUUID returns new OptUUID with value set to v.
func NewOptUUID(v UUID) OptUUID {
	return OptUUID{
		Value: v,
		Set:   true,
	}
}

// OptUUID is optional UUID.
type OptUUID struct {
	Value UUID
	Set   bool
}

// IsSet returns true if OptUUID was set.
func (o OptUUID) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptUUID) Reset() {
	var v UUID
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptUUID) SetTo(v UUID) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptUUID) Get() (v UUID, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptUUID) Or(d UUID) UUID {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// Ref: #/components/schemas/Owner
type Owner struct {
	Kind jx.Raw `json:"kind"`
	ID   string `json:"id"`
}

// GetKind returns the value of Kind.
func (s *Owner) GetKind() jx.Raw {
	return s.Kind
}

// GetID returns the value of ID.
func (s *Owner) GetID() string {
	return s.ID
}

// SetKind sets the value of Kind.
func (s *Owner) SetKind(val jx.Raw) {
	s.Kind = val
}

// SetID sets the value of ID.
func (s *Owner) SetID(val string) {
	s.ID = val
}

// Ref: #/components/schemas/PortableSnapshot
type PortableSnapshot struct {
	ID             UUID        `json:"id"`
	WorkspaceId    UUID        `json:"workspaceId"`
	Generation     int         `json:"generation"`
	State          jx.Raw      `json:"state"`
	ManifestDigest OptString   `json:"manifestDigest"`
	CreatedAt      OptDateTime `json:"createdAt"`
}

// GetID returns the value of ID.
func (s *PortableSnapshot) GetID() UUID {
	return s.ID
}

// GetWorkspaceId returns the value of WorkspaceId.
func (s *PortableSnapshot) GetWorkspaceId() UUID {
	return s.WorkspaceId
}

// GetGeneration returns the value of Generation.
func (s *PortableSnapshot) GetGeneration() int {
	return s.Generation
}

// GetState returns the value of State.
func (s *PortableSnapshot) GetState() jx.Raw {
	return s.State
}

// GetManifestDigest returns the value of ManifestDigest.
func (s *PortableSnapshot) GetManifestDigest() OptString {
	return s.ManifestDigest
}

// GetCreatedAt returns the value of CreatedAt.
func (s *PortableSnapshot) GetCreatedAt() OptDateTime {
	return s.CreatedAt
}

// SetID sets the value of ID.
func (s *PortableSnapshot) SetID(val UUID) {
	s.ID = val
}

// SetWorkspaceId sets the value of WorkspaceId.
func (s *PortableSnapshot) SetWorkspaceId(val UUID) {
	s.WorkspaceId = val
}

// SetGeneration sets the value of Generation.
func (s *PortableSnapshot) SetGeneration(val int) {
	s.Generation = val
}

// SetState sets the value of State.
func (s *PortableSnapshot) SetState(val jx.Raw) {
	s.State = val
}

// SetManifestDigest sets the value of ManifestDigest.
func (s *PortableSnapshot) SetManifestDigest(val OptString) {
	s.ManifestDigest = val
}

// SetCreatedAt sets the value of CreatedAt.
func (s *PortableSnapshot) SetCreatedAt(val OptDateTime) {
	s.CreatedAt = val
}

// Ref: #/components/schemas/Problem
type Problem struct {
	Type            string    `json:"type"`
	Title           string    `json:"title"`
	Status          int       `json:"status"`
	Detail          OptString `json:"detail"`
	Instance        OptString `json:"instance"`
	Code            OptString `json:"code"`
	TraceId         OptString `json:"traceId"`
	AdditionalProps ProblemAdditional
}

// GetType returns the value of Type.
func (s *Problem) GetType() string {
	return s.Type
}

// GetTitle returns the value of Title.
func (s *Problem) GetTitle() string {
	return s.Title
}

// GetStatus returns the value of Status.
func (s *Problem) GetStatus() int {
	return s.Status
}

// GetDetail returns the value of Detail.
func (s *Problem) GetDetail() OptString {
	return s.Detail
}

// GetInstance returns the value of Instance.
func (s *Problem) GetInstance() OptString {
	return s.Instance
}

// GetCode returns the value of Code.
func (s *Problem) GetCode() OptString {
	return s.Code
}

// GetTraceId returns the value of TraceId.
func (s *Problem) GetTraceId() OptString {
	return s.TraceId
}

// GetAdditionalProps returns the value of AdditionalProps.
func (s *Problem) GetAdditionalProps() ProblemAdditional {
	return s.AdditionalProps
}

// SetType sets the value of Type.
func (s *Problem) SetType(val string) {
	s.Type = val
}

// SetTitle sets the value of Title.
func (s *Problem) SetTitle(val string) {
	s.Title = val
}

// SetStatus sets the value of Status.
func (s *Problem) SetStatus(val int) {
	s.Status = val
}

// SetDetail sets the value of Detail.
func (s *Problem) SetDetail(val OptString) {
	s.Detail = val
}

// SetInstance sets the value of Instance.
func (s *Problem) SetInstance(val OptString) {
	s.Instance = val
}

// SetCode sets the value of Code.
func (s *Problem) SetCode(val OptString) {
	s.Code = val
}

// SetTraceId sets the value of TraceId.
func (s *Problem) SetTraceId(val OptString) {
	s.TraceId = val
}

// SetAdditionalProps sets the value of AdditionalProps.
func (s *Problem) SetAdditionalProps(val ProblemAdditional) {
	s.AdditionalProps = val
}

type ProblemAdditional map[string]jx.Raw

func (s *ProblemAdditional) init() ProblemAdditional {
	m := *s
	if m == nil {
		m = map[string]jx.Raw{}
		*s = m
	}
	return m
}

// ProblemStatusCode wraps Problem with StatusCode.
type ProblemStatusCode struct {
	StatusCode int
	Response   Problem
}

// GetStatusCode returns the value of StatusCode.
func (s *ProblemStatusCode) GetStatusCode() int {
	return s.StatusCode
}

// GetResponse returns the value of Response.
func (s *ProblemStatusCode) GetResponse() Problem {
	return s.Response
}

// SetStatusCode sets the value of StatusCode.
func (s *ProblemStatusCode) SetStatusCode(val int) {
	s.StatusCode = val
}

// SetResponse sets the value of Response.
func (s *ProblemStatusCode) SetResponse(val Problem) {
	s.Response = val
}

type RefreshSourcesReq struct {
	ComponentIds           []UUID `json:"componentIds"`
	ExpectedHeadGeneration int    `json:"expectedHeadGeneration"`
	ConflictPolicy         jx.Raw `json:"conflictPolicy"`
}

// GetComponentIds returns the value of ComponentIds.
func (s *RefreshSourcesReq) GetComponentIds() []UUID {
	return s.ComponentIds
}

// GetExpectedHeadGeneration returns the value of ExpectedHeadGeneration.
func (s *RefreshSourcesReq) GetExpectedHeadGeneration() int {
	return s.ExpectedHeadGeneration
}

// GetConflictPolicy returns the value of ConflictPolicy.
func (s *RefreshSourcesReq) GetConflictPolicy() jx.Raw {
	return s.ConflictPolicy
}

// SetComponentIds sets the value of ComponentIds.
func (s *RefreshSourcesReq) SetComponentIds(val []UUID) {
	s.ComponentIds = val
}

// SetExpectedHeadGeneration sets the value of ExpectedHeadGeneration.
func (s *RefreshSourcesReq) SetExpectedHeadGeneration(val int) {
	s.ExpectedHeadGeneration = val
}

// SetConflictPolicy sets the value of ConflictPolicy.
func (s *RefreshSourcesReq) SetConflictPolicy(val jx.Raw) {
	s.ConflictPolicy = val
}

type RestoreWorkspaceReq struct {
	Target TargetContext `json:"target"`
}

// GetTarget returns the value of Target.
func (s *RestoreWorkspaceReq) GetTarget() TargetContext {
	return s.Target
}

// SetTarget sets the value of Target.
func (s *RestoreWorkspaceReq) SetTarget(val TargetContext) {
	s.Target = val
}

// Ref: #/components/schemas/SourceBinding
type SourceBinding struct {
	Ref      url.URL   `json:"ref"`
	Mode     jx.Raw    `json:"mode"`
	Revision OptString `json:"revision"`
}

// GetRef returns the value of Ref.
func (s *SourceBinding) GetRef() url.URL {
	return s.Ref
}

// GetMode returns the value of Mode.
func (s *SourceBinding) GetMode() jx.Raw {
	return s.Mode
}

// GetRevision returns the value of Revision.
func (s *SourceBinding) GetRevision() OptString {
	return s.Revision
}

// SetRef sets the value of Ref.
func (s *SourceBinding) SetRef(val url.URL) {
	s.Ref = val
}

// SetMode sets the value of Mode.
func (s *SourceBinding) SetMode(val jx.Raw) {
	s.Mode = val
}

// SetRevision sets the value of Revision.
func (s *SourceBinding) SetRevision(val OptString) {
	s.Revision = val
}

type StreamWorkspaceEventsOK struct {
	Data io.Reader
}

// Read reads data from the Data reader.
//
// Kept to satisfy the io.Reader interface.
func (s StreamWorkspaceEventsOK) Read(p []byte) (n int, err error) {
	if s.Data == nil {
		return 0, io.EOF
	}
	return s.Data.Read(p)
}

// Ref: #/components/schemas/TargetContext
type TargetContext struct {
	TargetId     string    `json:"targetId"`
	Region       string    `json:"region"`
	StorageClass string    `json:"storageClass"`
	Architecture OptString `json:"architecture"`
}

// GetTargetId returns the value of TargetId.
func (s *TargetContext) GetTargetId() string {
	return s.TargetId
}

// GetRegion returns the value of Region.
func (s *TargetContext) GetRegion() string {
	return s.Region
}

// GetStorageClass returns the value of StorageClass.
func (s *TargetContext) GetStorageClass() string {
	return s.StorageClass
}

// GetArchitecture returns the value of Architecture.
func (s *TargetContext) GetArchitecture() OptString {
	return s.Architecture
}

// SetTargetId sets the value of TargetId.
func (s *TargetContext) SetTargetId(val string) {
	s.TargetId = val
}

// SetRegion sets the value of Region.
func (s *TargetContext) SetRegion(val string) {
	s.Region = val
}

// SetStorageClass sets the value of StorageClass.
func (s *TargetContext) SetStorageClass(val string) {
	s.StorageClass = val
}

// SetArchitecture sets the value of Architecture.
func (s *TargetContext) SetArchitecture(val OptString) {
	s.Architecture = val
}

type UUID uuid.UUID

// Ref: #/components/schemas/Workspace
type Workspace struct {
	ID             UUID           `json:"id"`
	Name           Name           `json:"name"`
	Owner          Owner          `json:"owner"`
	State          WorkspaceState `json:"state"`
	StateVersion   int            `json:"stateVersion"`
	HeadGeneration OptInt         `json:"headGeneration"`
	Classification Classification `json:"classification"`
	Residency      []string       `json:"residency"`
	CreatedAt      time.Time      `json:"createdAt"`
}

// GetID returns the value of ID.
func (s *Workspace) GetID() UUID {
	return s.ID
}

// GetName returns the value of Name.
func (s *Workspace) GetName() Name {
	return s.Name
}

// GetOwner returns the value of Owner.
func (s *Workspace) GetOwner() Owner {
	return s.Owner
}

// GetState returns the value of State.
func (s *Workspace) GetState() WorkspaceState {
	return s.State
}

// GetStateVersion returns the value of StateVersion.
func (s *Workspace) GetStateVersion() int {
	return s.StateVersion
}

// GetHeadGeneration returns the value of HeadGeneration.
func (s *Workspace) GetHeadGeneration() OptInt {
	return s.HeadGeneration
}

// GetClassification returns the value of Classification.
func (s *Workspace) GetClassification() Classification {
	return s.Classification
}

// GetResidency returns the value of Residency.
func (s *Workspace) GetResidency() []string {
	return s.Residency
}

// GetCreatedAt returns the value of CreatedAt.
func (s *Workspace) GetCreatedAt() time.Time {
	return s.CreatedAt
}

// SetID sets the value of ID.
func (s *Workspace) SetID(val UUID) {
	s.ID = val
}

// SetName sets the value of Name.
func (s *Workspace) SetName(val Name) {
	s.Name = val
}

// SetOwner sets the value of Owner.
func (s *Workspace) SetOwner(val Owner) {
	s.Owner = val
}

// SetState sets the value of State.
func (s *Workspace) SetState(val WorkspaceState) {
	s.State = val
}

// SetStateVersion sets the value of StateVersion.
func (s *Workspace) SetStateVersion(val int) {
	s.StateVersion = val
}

// SetHeadGeneration sets the value of HeadGeneration.
func (s *Workspace) SetHeadGeneration(val OptInt) {
	s.HeadGeneration = val
}

// SetClassification sets the value of Classification.
func (s *Workspace) SetClassification(val Classification) {
	s.Classification = val
}

// SetResidency sets the value of Residency.
func (s *Workspace) SetResidency(val []string) {
	s.Residency = val
}

// SetCreatedAt sets the value of CreatedAt.
func (s *Workspace) SetCreatedAt(val time.Time) {
	s.CreatedAt = val
}

// WorkspaceHeaders wraps Workspace with response headers.
type WorkspaceHeaders struct {
	Location OptString
	Response Workspace
}

// GetLocation returns the value of Location.
func (s *WorkspaceHeaders) GetLocation() OptString {
	return s.Location
}

// GetResponse returns the value of Response.
func (s *WorkspaceHeaders) GetResponse() Workspace {
	return s.Response
}

// SetLocation sets the value of Location.
func (s *WorkspaceHeaders) SetLocation(val OptString) {
	s.Location = val
}

// SetResponse sets the value of Response.
func (s *WorkspaceHeaders) SetResponse(val Workspace) {
	s.Response = val
}

// Ref: #/components/schemas/WorkspacePage
type WorkspacePage struct {
	Items      []Workspace  `json:"items"`
	NextCursor OptNilString `json:"nextCursor"`
}

// GetItems returns the value of Items.
func (s *WorkspacePage) GetItems() []Workspace {
	return s.Items
}

// GetNextCursor returns the value of NextCursor.
func (s *WorkspacePage) GetNextCursor() OptNilString {
	return s.NextCursor
}

// SetItems sets the value of Items.
func (s *WorkspacePage) SetItems(val []Workspace) {
	s.Items = val
}

// SetNextCursor sets the value of NextCursor.
func (s *WorkspacePage) SetNextCursor(val OptNilString) {
	s.NextCursor = val
}

type WorkspaceState jx.Raw
