// Code generated by ogen, DO NOT EDIT.

package openapi

// OperationName is the ogen operation name
type OperationName = string

const (
	AddComponentOperation              OperationName = "AddComponent"
	ArchiveWorkspaceOperation          OperationName = "ArchiveWorkspace"
	CheckpointMaterializationOperation OperationName = "CheckpointMaterialization"
	CommitMaterializationOperation     OperationName = "CommitMaterialization"
	CreateMaterializationOperation     OperationName = "CreateMaterialization"
	CreatePortableSnapshotOperation    OperationName = "CreatePortableSnapshot"
	CreateWorkspaceOperation           OperationName = "CreateWorkspace"
	DeleteWorkspaceOperation           OperationName = "DeleteWorkspace"
	ForkWorkspaceOperation             OperationName = "ForkWorkspace"
	GetComponentOperation              OperationName = "GetComponent"
	GetGenerationOperation             OperationName = "GetGeneration"
	GetImportOperation                 OperationName = "GetImport"
	GetMaterializationOperation        OperationName = "GetMaterialization"
	GetWorkspaceOperation              OperationName = "GetWorkspace"
	ImportSourceOperation              OperationName = "ImportSource"
	ListComponentsOperation            OperationName = "ListComponents"
	ListGenerationsOperation           OperationName = "ListGenerations"
	ListPortableSnapshotsOperation     OperationName = "ListPortableSnapshots"
	ListWorkspacesOperation            OperationName = "ListWorkspaces"
	RefreshSourcesOperation            OperationName = "RefreshSources"
	ReleaseMaterializationOperation    OperationName = "ReleaseMaterialization"
	RestoreWorkspaceOperation          OperationName = "RestoreWorkspace"
	StreamWorkspaceEventsOperation     OperationName = "StreamWorkspaceEvents"
)
