// Code generated by ogen, DO NOT EDIT.

package openapi

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// AddComponent implements addComponent operation.
//
// POST /v1/workspaces/{workspace_id}/components
func (UnimplementedHandler) AddComponent(ctx context.Context, req *ComponentInput, params AddComponentParams) (r *Operation, _ error) {
	return r, ht.ErrNotImplemented
}

// ArchiveWorkspace implements archiveWorkspace operation.
//
// POST /v1/workspaces/{workspace_id}/archive
func (UnimplementedHandler) ArchiveWorkspace(ctx context.Context, params ArchiveWorkspaceParams) (r *Operation, _ error) {
	return r, ht.ErrNotImplemented
}

// CheckpointMaterialization implements checkpointMaterialization operation.
//
// POST /v1/materializations/{materialization_id}/checkpoint
func (UnimplementedHandler) CheckpointMaterialization(ctx context.Context, req *FencedRequest, params CheckpointMaterializationParams) (r *Operation, _ error) {
	return r, ht.ErrNotImplemented
}

// CommitMaterialization implements commitMaterialization operation.
//
// POST /v1/materializations/{materialization_id}/commit
func (UnimplementedHandler) CommitMaterialization(ctx context.Context, req *CommitRequest, params CommitMaterializationParams) (r *Generation, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateMaterialization implements createMaterialization operation.
//
// POST /v1/workspaces/{workspace_id}/materializations
func (UnimplementedHandler) CreateMaterialization(ctx context.Context, req *CreateMaterialization, params CreateMaterializationParams) (r *Materialization, _ error) {
	return r, ht.ErrNotImplemented
}

// CreatePortableSnapshot implements createPortableSnapshot operation.
//
// POST /v1/workspaces/{workspace_id}/snapshots
func (UnimplementedHandler) CreatePortableSnapshot(ctx context.Context, req *CreatePortableSnapshotReq, params CreatePortableSnapshotParams) (r *Operation, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateWorkspace implements createWorkspace operation.
//
// POST /v1/workspaces
func (UnimplementedHandler) CreateWorkspace(ctx context.Context, req *CreateWorkspace, params CreateWorkspaceParams) (r *WorkspaceHeaders, _ error) {
	return r, ht.ErrNotImplemented
}

// DeleteWorkspace implements deleteWorkspace operation.
//
// DELETE /v1/workspaces/{workspace_id}
func (UnimplementedHandler) DeleteWorkspace(ctx context.Context, params DeleteWorkspaceParams) (r *Operation, _ error) {
	return r, ht.ErrNotImplemented
}

// ForkWorkspace implements forkWorkspace operation.
//
// POST /v1/workspaces/{workspace_id}/forks
func (UnimplementedHandler) ForkWorkspace(ctx context.Context, req *ForkWorkspaceReq, params ForkWorkspaceParams) (r *Operation, _ error) {
	return r, ht.ErrNotImplemented
}

// GetComponent implements getComponent operation.
//
// GET /v1/workspaces/{workspace_id}/components/{component_id}
func (UnimplementedHandler) GetComponent(ctx context.Context, params GetComponentParams) (r *Component, _ error) {
	return r, ht.ErrNotImplemented
}

// GetGeneration implements getGeneration operation.
//
// GET /v1/workspaces/{workspace_id}/generations/{generation}
func (UnimplementedHandler) GetGeneration(ctx context.Context, params GetGenerationParams) (r *Generation, _ error) {
	return r, ht.ErrNotImplemented
}

// GetImport implements getImport operation.
//
// GET /v1/imports/{import_id}
func (UnimplementedHandler) GetImport(ctx context.Context, params GetImportParams) (r *Operation, _ error) {
	return r, ht.ErrNotImplemented
}

// GetMaterialization implements getMaterialization operation.
//
// GET /v1/materializations/{materialization_id}
func (UnimplementedHandler) GetMaterialization(ctx context.Context, params GetMaterializationParams) (r *Materialization, _ error) {
	return r, ht.ErrNotImplemented
}

// GetWorkspace implements getWorkspace operation.
//
// GET /v1/workspaces/{workspace_id}
func (UnimplementedHandler) GetWorkspace(ctx context.Context, params GetWorkspaceParams) (r *Workspace, _ error) {
	return r, ht.ErrNotImplemented
}

// ImportSource implements importSource operation.
//
// POST /v1/workspaces/{workspace_id}/imports
func (UnimplementedHandler) ImportSource(ctx context.Context, req *ImportRequest, params ImportSourceParams) (r *Operation, _ error) {
	return r, ht.ErrNotImplemented
}

// ListComponents implements listComponents operation.
//
// GET /v1/workspaces/{workspace_id}/components
func (UnimplementedHandler) ListComponents(ctx context.Context, params ListComponentsParams) (r []Component, _ error) {
	return r, ht.ErrNotImplemented
}

// ListGenerations implements listGenerations operation.
//
// GET /v1/workspaces/{workspace_id}/generations
func (UnimplementedHandler) ListGenerations(ctx context.Context, params ListGenerationsParams) (r []Generation, _ error) {
	return r, ht.ErrNotImplemented
}

// ListPortableSnapshots implements listPortableSnapshots operation.
//
// GET /v1/workspaces/{workspace_id}/snapshots
func (UnimplementedHandler) ListPortableSnapshots(ctx context.Context, params ListPortableSnapshotsParams) (r []PortableSnapshot, _ error) {
	return r, ht.ErrNotImplemented
}

// ListWorkspaces implements listWorkspaces operation.
//
// GET /v1/workspaces
func (UnimplementedHandler) ListWorkspaces(ctx context.Context, params ListWorkspacesParams) (r *WorkspacePage, _ error) {
	return r, ht.ErrNotImplemented
}

// RefreshSources implements refreshSources operation.
//
// POST /v1/workspaces/{workspace_id}/refreshes
func (UnimplementedHandler) RefreshSources(ctx context.Context, req *RefreshSourcesReq, params RefreshSourcesParams) (r *Operation, _ error) {
	return r, ht.ErrNotImplemented
}

// ReleaseMaterialization implements releaseMaterialization operation.
//
// DELETE /v1/materializations/{materialization_id}
func (UnimplementedHandler) ReleaseMaterialization(ctx context.Context, params ReleaseMaterializationParams) (r *Operation, _ error) {
	return r, ht.ErrNotImplemented
}

// RestoreWorkspace implements restoreWorkspace operation.
//
// POST /v1/workspaces/{workspace_id}/restore
func (UnimplementedHandler) RestoreWorkspace(ctx context.Context, req *RestoreWorkspaceReq, params RestoreWorkspaceParams) (r *Operation, _ error) {
	return r, ht.ErrNotImplemented
}

// StreamWorkspaceEvents implements streamWorkspaceEvents operation.
//
// GET /v1/workspaces/{workspace_id}/events
func (UnimplementedHandler) StreamWorkspaceEvents(ctx context.Context, params StreamWorkspaceEventsParams) (r StreamWorkspaceEventsOK, _ error) {
	return r, ht.ErrNotImplemented
}

// NewError creates *ProblemStatusCode from error returned by handler.
//
// Used for common default response.
func (UnimplementedHandler) NewError(ctx context.Context, err error) (r *ProblemStatusCode) {
	r = new(ProblemStatusCode)
	return r
}
