// Code generated by ogen, DO NOT EDIT.

package openapi

import (
	"context"
)

// Handler handles operations described by OpenAPI v3 specification.
type Handler interface {
	// AddComponent implements addComponent operation.
	//
	// POST /v1/workspaces/{workspace_id}/components
	AddComponent(ctx context.Context, req *ComponentInput, params AddComponentParams) (*Operation, error)
	// ArchiveWorkspace implements archiveWorkspace operation.
	//
	// POST /v1/workspaces/{workspace_id}/archive
	ArchiveWorkspace(ctx context.Context, params ArchiveWorkspaceParams) (*Operation, error)
	// CheckpointMaterialization implements checkpointMaterialization operation.
	//
	// POST /v1/materializations/{materialization_id}/checkpoint
	CheckpointMaterialization(ctx context.Context, req *FencedRequest, params CheckpointMaterializationParams) (*Operation, error)
	// CommitMaterialization implements commitMaterialization operation.
	//
	// POST /v1/materializations/{materialization_id}/commit
	CommitMaterialization(ctx context.Context, req *CommitRequest, params CommitMaterializationParams) (*Generation, error)
	// CreateMaterialization implements createMaterialization operation.
	//
	// POST /v1/workspaces/{workspace_id}/materializations
	CreateMaterialization(ctx context.Context, req *CreateMaterialization, params CreateMaterializationParams) (*Materialization, error)
	// CreatePortableSnapshot implements createPortableSnapshot operation.
	//
	// POST /v1/workspaces/{workspace_id}/snapshots
	CreatePortableSnapshot(ctx context.Context, req *CreatePortableSnapshotReq, params CreatePortableSnapshotParams) (*Operation, error)
	// CreateWorkspace implements createWorkspace operation.
	//
	// POST /v1/workspaces
	CreateWorkspace(ctx context.Context, req *CreateWorkspace, params CreateWorkspaceParams) (*WorkspaceHeaders, error)
	// DeleteWorkspace implements deleteWorkspace operation.
	//
	// DELETE /v1/workspaces/{workspace_id}
	DeleteWorkspace(ctx context.Context, params DeleteWorkspaceParams) (*Operation, error)
	// ForkWorkspace implements forkWorkspace operation.
	//
	// POST /v1/workspaces/{workspace_id}/forks
	ForkWorkspace(ctx context.Context, req *ForkWorkspaceReq, params ForkWorkspaceParams) (*Operation, error)
	// GetComponent implements getComponent operation.
	//
	// GET /v1/workspaces/{workspace_id}/components/{component_id}
	GetComponent(ctx context.Context, params GetComponentParams) (*Component, error)
	// GetGeneration implements getGeneration operation.
	//
	// GET /v1/workspaces/{workspace_id}/generations/{generation}
	GetGeneration(ctx context.Context, params GetGenerationParams) (*Generation, error)
	// GetImport implements getImport operation.
	//
	// GET /v1/imports/{import_id}
	GetImport(ctx context.Context, params GetImportParams) (*Operation, error)
	// GetMaterialization implements getMaterialization operation.
	//
	// GET /v1/materializations/{materialization_id}
	GetMaterialization(ctx context.Context, params GetMaterializationParams) (*Materialization, error)
	// GetWorkspace implements getWorkspace operation.
	//
	// GET /v1/workspaces/{workspace_id}
	GetWorkspace(ctx context.Context, params GetWorkspaceParams) (*Workspace, error)
	// ImportSource implements importSource operation.
	//
	// POST /v1/workspaces/{workspace_id}/imports
	ImportSource(ctx context.Context, req *ImportRequest, params ImportSourceParams) (*Operation, error)
	// ListComponents implements listComponents operation.
	//
	// GET /v1/workspaces/{workspace_id}/components
	ListComponents(ctx context.Context, params ListComponentsParams) ([]Component, error)
	// ListGenerations implements listGenerations operation.
	//
	// GET /v1/workspaces/{workspace_id}/generations
	ListGenerations(ctx context.Context, params ListGenerationsParams) ([]Generation, error)
	// ListPortableSnapshots implements listPortableSnapshots operation.
	//
	// GET /v1/workspaces/{workspace_id}/snapshots
	ListPortableSnapshots(ctx context.Context, params ListPortableSnapshotsParams) ([]PortableSnapshot, error)
	// ListWorkspaces implements listWorkspaces operation.
	//
	// GET /v1/workspaces
	ListWorkspaces(ctx context.Context, params ListWorkspacesParams) (*WorkspacePage, error)
	// RefreshSources implements refreshSources operation.
	//
	// POST /v1/workspaces/{workspace_id}/refreshes
	RefreshSources(ctx context.Context, req *RefreshSourcesReq, params RefreshSourcesParams) (*Operation, error)
	// ReleaseMaterialization implements releaseMaterialization operation.
	//
	// DELETE /v1/materializations/{materialization_id}
	ReleaseMaterialization(ctx context.Context, params ReleaseMaterializationParams) (*Operation, error)
	// RestoreWorkspace implements restoreWorkspace operation.
	//
	// POST /v1/workspaces/{workspace_id}/restore
	RestoreWorkspace(ctx context.Context, req *RestoreWorkspaceReq, params RestoreWorkspaceParams) (*Operation, error)
	// StreamWorkspaceEvents implements streamWorkspaceEvents operation.
	//
	// GET /v1/workspaces/{workspace_id}/events
	StreamWorkspaceEvents(ctx context.Context, params StreamWorkspaceEventsParams) (StreamWorkspaceEventsOK, error)
	// NewError creates *ProblemStatusCode from error returned by handler.
	//
	// Used for common default response.
	NewError(ctx context.Context, err error) *ProblemStatusCode
}

// Server implements http server based on OpenAPI v3 specification and
// calls Handler to handle requests.
type Server struct {
	h Handler
	baseServer
}

// NewServer creates new Server.
func NewServer(h Handler, opts ...ServerOption) (*Server, error) {
	s, err := newServerConfig(opts...).baseServer()
	if err != nil {
		return nil, err
	}
	return &Server{
		h:          h,
		baseServer: s,
	}, nil
}
