// Code generated by ogen, DO NOT EDIT.

package openapi

import "github.com/ogen-go/ogen/validate"

// Equal compares two CreateMaterializationComponentAccessItem instances for equality.
// The depth parameter prevents infinite recursion on nested objects.
func (a CreateMaterializationComponentAccessItem) Equal(b CreateMaterializationComponentAccessItem, depth int) bool {
	if depth > 10 {
		panic(&validate.DepthLimitError{
			MaxDepth: 10,
			TypeName: "CreateMaterializationComponentAccessItem",
		})
	}

	if a.ComponentId != b.ComponentId {
		return false
	}
	if a.Mode != b.Mode {
		return false
	}
	return true
}
