// Code generated by ogen, DO NOT EDIT.

package openapi

import (
	"net/http"
	"net/url"

	"github.com/go-faster/errors"
	"github.com/google/uuid"
	"github.com/ogen-go/ogen/conv"
	"github.com/ogen-go/ogen/middleware"
	"github.com/ogen-go/ogen/ogenerrors"
	"github.com/ogen-go/ogen/uri"
	"github.com/ogen-go/ogen/validate"
)

// AddComponentParams is parameters of addComponent operation.
type AddComponentParams struct {
	IdempotencyKey string
	WorkspaceID    UUID
}

func unpackAddComponentParams(packed middleware.Parameters) (params AddComponentParams) {
	{
		key := middleware.ParameterKey{
			Name: "Idempotency-Key",
			In:   "header",
		}
		params.IdempotencyKey = packed[key].(string)
	}
	{
		key := middleware.ParameterKey{
			Name: "workspace_id",
			In:   "path",
		}
		params.WorkspaceID = packed[key].(UUID)
	}
	return params
}

func decodeAddComponentParams(args [1]string, argsEscaped bool, r *http.Request) (params AddComponentParams, _ error) {
	h := uri.NewHeaderDecoder(r.Header)
	// Decode header: Idempotency-Key.
	if err := func() error {
		cfg := uri.HeaderParameterDecodingConfig{
			Name:    "Idempotency-Key",
			Explode: false,
		}
		if err := h.HasParam(cfg); err == nil {
			if err := h.DecodeParam(cfg, func(d uri.Decoder) error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToString(val)
				if err != nil {
					return err
				}

				params.IdempotencyKey = c
				return nil
			}); err != nil {
				return err
			}
			if err := func() error {
				if err := (validate.String{
					MinLength:     16,
					MinLengthSet:  true,
					MaxLength:     128,
					MaxLengthSet:  true,
					Email:         false,
					Hostname:      false,
					Regex:         nil,
					MinNumeric:    0,
					MinNumericSet: false,
					MaxNumeric:    0,
					MaxNumericSet: false,
				}).Validate(string(params.IdempotencyKey)); err != nil {
					return errors.Wrap(err, "string")
				}
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return err
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "Idempotency-Key",
			In:   "header",
			Err:  err,
		}
	}
	// Decode path: workspace_id.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "workspace_id",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				var paramsDotWorkspaceIDVal uuid.UUID
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToUUID(val)
					if err != nil {
						return err
					}

					paramsDotWorkspaceIDVal = c
					return nil
				}(); err != nil {
					return err
				}
				params.WorkspaceID = UUID(paramsDotWorkspaceIDVal)
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "workspace_id",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// ArchiveWorkspaceParams is parameters of archiveWorkspace operation.
type ArchiveWorkspaceParams struct {
	IdempotencyKey string
	WorkspaceID    UUID
}

func unpackArchiveWorkspaceParams(packed middleware.Parameters) (params ArchiveWorkspaceParams) {
	{
		key := middleware.ParameterKey{
			Name: "Idempotency-Key",
			In:   "header",
		}
		params.IdempotencyKey = packed[key].(string)
	}
	{
		key := middleware.ParameterKey{
			Name: "workspace_id",
			In:   "path",
		}
		params.WorkspaceID = packed[key].(UUID)
	}
	return params
}

func decodeArchiveWorkspaceParams(args [1]string, argsEscaped bool, r *http.Request) (params ArchiveWorkspaceParams, _ error) {
	h := uri.NewHeaderDecoder(r.Header)
	// Decode header: Idempotency-Key.
	if err := func() error {
		cfg := uri.HeaderParameterDecodingConfig{
			Name:    "Idempotency-Key",
			Explode: false,
		}
		if err := h.HasParam(cfg); err == nil {
			if err := h.DecodeParam(cfg, func(d uri.Decoder) error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToString(val)
				if err != nil {
					return err
				}

				params.IdempotencyKey = c
				return nil
			}); err != nil {
				return err
			}
			if err := func() error {
				if err := (validate.String{
					MinLength:     16,
					MinLengthSet:  true,
					MaxLength:     128,
					MaxLengthSet:  true,
					Email:         false,
					Hostname:      false,
					Regex:         nil,
					MinNumeric:    0,
					MinNumericSet: false,
					MaxNumeric:    0,
					MaxNumericSet: false,
				}).Validate(string(params.IdempotencyKey)); err != nil {
					return errors.Wrap(err, "string")
				}
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return err
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "Idempotency-Key",
			In:   "header",
			Err:  err,
		}
	}
	// Decode path: workspace_id.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "workspace_id",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				var paramsDotWorkspaceIDVal uuid.UUID
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToUUID(val)
					if err != nil {
						return err
					}

					paramsDotWorkspaceIDVal = c
					return nil
				}(); err != nil {
					return err
				}
				params.WorkspaceID = UUID(paramsDotWorkspaceIDVal)
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "workspace_id",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// CheckpointMaterializationParams is parameters of checkpointMaterialization operation.
type CheckpointMaterializationParams struct {
	IdempotencyKey    string
	MaterializationID UUID
}

func unpackCheckpointMaterializationParams(packed middleware.Parameters) (params CheckpointMaterializationParams) {
	{
		key := middleware.ParameterKey{
			Name: "Idempotency-Key",
			In:   "header",
		}
		params.IdempotencyKey = packed[key].(string)
	}
	{
		key := middleware.ParameterKey{
			Name: "materialization_id",
			In:   "path",
		}
		params.MaterializationID = packed[key].(UUID)
	}
	return params
}

func decodeCheckpointMaterializationParams(args [1]string, argsEscaped bool, r *http.Request) (params CheckpointMaterializationParams, _ error) {
	h := uri.NewHeaderDecoder(r.Header)
	// Decode header: Idempotency-Key.
	if err := func() error {
		cfg := uri.HeaderParameterDecodingConfig{
			Name:    "Idempotency-Key",
			Explode: false,
		}
		if err := h.HasParam(cfg); err == nil {
			if err := h.DecodeParam(cfg, func(d uri.Decoder) error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToString(val)
				if err != nil {
					return err
				}

				params.IdempotencyKey = c
				return nil
			}); err != nil {
				return err
			}
			if err := func() error {
				if err := (validate.String{
					MinLength:     16,
					MinLengthSet:  true,
					MaxLength:     128,
					MaxLengthSet:  true,
					Email:         false,
					Hostname:      false,
					Regex:         nil,
					MinNumeric:    0,
					MinNumericSet: false,
					MaxNumeric:    0,
					MaxNumericSet: false,
				}).Validate(string(params.IdempotencyKey)); err != nil {
					return errors.Wrap(err, "string")
				}
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return err
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "Idempotency-Key",
			In:   "header",
			Err:  err,
		}
	}
	// Decode path: materialization_id.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "materialization_id",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				var paramsDotMaterializationIDVal uuid.UUID
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToUUID(val)
					if err != nil {
						return err
					}

					paramsDotMaterializationIDVal = c
					return nil
				}(); err != nil {
					return err
				}
				params.MaterializationID = UUID(paramsDotMaterializationIDVal)
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "materialization_id",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// CommitMaterializationParams is parameters of commitMaterialization operation.
type CommitMaterializationParams struct {
	IdempotencyKey    string
	MaterializationID UUID
}

func unpackCommitMaterializationParams(packed middleware.Parameters) (params CommitMaterializationParams) {
	{
		key := middleware.ParameterKey{
			Name: "Idempotency-Key",
			In:   "header",
		}
		params.IdempotencyKey = packed[key].(string)
	}
	{
		key := middleware.ParameterKey{
			Name: "materialization_id",
			In:   "path",
		}
		params.MaterializationID = packed[key].(UUID)
	}
	return params
}

func decodeCommitMaterializationParams(args [1]string, argsEscaped bool, r *http.Request) (params CommitMaterializationParams, _ error) {
	h := uri.NewHeaderDecoder(r.Header)
	// Decode header: Idempotency-Key.
	if err := func() error {
		cfg := uri.HeaderParameterDecodingConfig{
			Name:    "Idempotency-Key",
			Explode: false,
		}
		if err := h.HasParam(cfg); err == nil {
			if err := h.DecodeParam(cfg, func(d uri.Decoder) error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToString(val)
				if err != nil {
					return err
				}

				params.IdempotencyKey = c
				return nil
			}); err != nil {
				return err
			}
			if err := func() error {
				if err := (validate.String{
					MinLength:     16,
					MinLengthSet:  true,
					MaxLength:     128,
					MaxLengthSet:  true,
					Email:         false,
					Hostname:      false,
					Regex:         nil,
					MinNumeric:    0,
					MinNumericSet: false,
					MaxNumeric:    0,
					MaxNumericSet: false,
				}).Validate(string(params.IdempotencyKey)); err != nil {
					return errors.Wrap(err, "string")
				}
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return err
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "Idempotency-Key",
			In:   "header",
			Err:  err,
		}
	}
	// Decode path: materialization_id.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "materialization_id",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				var paramsDotMaterializationIDVal uuid.UUID
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToUUID(val)
					if err != nil {
						return err
					}

					paramsDotMaterializationIDVal = c
					return nil
				}(); err != nil {
					return err
				}
				params.MaterializationID = UUID(paramsDotMaterializationIDVal)
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "materialization_id",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// CreateMaterializationParams is parameters of createMaterialization operation.
type CreateMaterializationParams struct {
	IdempotencyKey string
	WorkspaceID    UUID
}

func unpackCreateMaterializationParams(packed middleware.Parameters) (params CreateMaterializationParams) {
	{
		key := middleware.ParameterKey{
			Name: "Idempotency-Key",
			In:   "header",
		}
		params.IdempotencyKey = packed[key].(string)
	}
	{
		key := middleware.ParameterKey{
			Name: "workspace_id",
			In:   "path",
		}
		params.WorkspaceID = packed[key].(UUID)
	}
	return params
}

func decodeCreateMaterializationParams(args [1]string, argsEscaped bool, r *http.Request) (params CreateMaterializationParams, _ error) {
	h := uri.NewHeaderDecoder(r.Header)
	// Decode header: Idempotency-Key.
	if err := func() error {
		cfg := uri.HeaderParameterDecodingConfig{
			Name:    "Idempotency-Key",
			Explode: false,
		}
		if err := h.HasParam(cfg); err == nil {
			if err := h.DecodeParam(cfg, func(d uri.Decoder) error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToString(val)
				if err != nil {
					return err
				}

				params.IdempotencyKey = c
				return nil
			}); err != nil {
				return err
			}
			if err := func() error {
				if err := (validate.String{
					MinLength:     16,
					MinLengthSet:  true,
					MaxLength:     128,
					MaxLengthSet:  true,
					Email:         false,
					Hostname:      false,
					Regex:         nil,
					MinNumeric:    0,
					MinNumericSet: false,
					MaxNumeric:    0,
					MaxNumericSet: false,
				}).Validate(string(params.IdempotencyKey)); err != nil {
					return errors.Wrap(err, "string")
				}
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return err
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "Idempotency-Key",
			In:   "header",
			Err:  err,
		}
	}
	// Decode path: workspace_id.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "workspace_id",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				var paramsDotWorkspaceIDVal uuid.UUID
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToUUID(val)
					if err != nil {
						return err
					}

					paramsDotWorkspaceIDVal = c
					return nil
				}(); err != nil {
					return err
				}
				params.WorkspaceID = UUID(paramsDotWorkspaceIDVal)
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "workspace_id",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// CreatePortableSnapshotParams is parameters of createPortableSnapshot operation.
type CreatePortableSnapshotParams struct {
	IdempotencyKey string
	WorkspaceID    UUID
}

func unpackCreatePortableSnapshotParams(packed middleware.Parameters) (params CreatePortableSnapshotParams) {
	{
		key := middleware.ParameterKey{
			Name: "Idempotency-Key",
			In:   "header",
		}
		params.IdempotencyKey = packed[key].(string)
	}
	{
		key := middleware.ParameterKey{
			Name: "workspace_id",
			In:   "path",
		}
		params.WorkspaceID = packed[key].(UUID)
	}
	return params
}

func decodeCreatePortableSnapshotParams(args [1]string, argsEscaped bool, r *http.Request) (params CreatePortableSnapshotParams, _ error) {
	h := uri.NewHeaderDecoder(r.Header)
	// Decode header: Idempotency-Key.
	if err := func() error {
		cfg := uri.HeaderParameterDecodingConfig{
			Name:    "Idempotency-Key",
			Explode: false,
		}
		if err := h.HasParam(cfg); err == nil {
			if err := h.DecodeParam(cfg, func(d uri.Decoder) error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToString(val)
				if err != nil {
					return err
				}

				params.IdempotencyKey = c
				return nil
			}); err != nil {
				return err
			}
			if err := func() error {
				if err := (validate.String{
					MinLength:     16,
					MinLengthSet:  true,
					MaxLength:     128,
					MaxLengthSet:  true,
					Email:         false,
					Hostname:      false,
					Regex:         nil,
					MinNumeric:    0,
					MinNumericSet: false,
					MaxNumeric:    0,
					MaxNumericSet: false,
				}).Validate(string(params.IdempotencyKey)); err != nil {
					return errors.Wrap(err, "string")
				}
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return err
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "Idempotency-Key",
			In:   "header",
			Err:  err,
		}
	}
	// Decode path: workspace_id.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "workspace_id",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				var paramsDotWorkspaceIDVal uuid.UUID
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToUUID(val)
					if err != nil {
						return err
					}

					paramsDotWorkspaceIDVal = c
					return nil
				}(); err != nil {
					return err
				}
				params.WorkspaceID = UUID(paramsDotWorkspaceIDVal)
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "workspace_id",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// CreateWorkspaceParams is parameters of createWorkspace operation.
type CreateWorkspaceParams struct {
	IdempotencyKey string
}

func unpackCreateWorkspaceParams(packed middleware.Parameters) (params CreateWorkspaceParams) {
	{
		key := middleware.ParameterKey{
			Name: "Idempotency-Key",
			In:   "header",
		}
		params.IdempotencyKey = packed[key].(string)
	}
	return params
}

func decodeCreateWorkspaceParams(args [0]string, argsEscaped bool, r *http.Request) (params CreateWorkspaceParams, _ error) {
	h := uri.NewHeaderDecoder(r.Header)
	// Decode header: Idempotency-Key.
	if err := func() error {
		cfg := uri.HeaderParameterDecodingConfig{
			Name:    "Idempotency-Key",
			Explode: false,
		}
		if err := h.HasParam(cfg); err == nil {
			if err := h.DecodeParam(cfg, func(d uri.Decoder) error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToString(val)
				if err != nil {
					return err
				}

				params.IdempotencyKey = c
				return nil
			}); err != nil {
				return err
			}
			if err := func() error {
				if err := (validate.String{
					MinLength:     16,
					MinLengthSet:  true,
					MaxLength:     128,
					MaxLengthSet:  true,
					Email:         false,
					Hostname:      false,
					Regex:         nil,
					MinNumeric:    0,
					MinNumericSet: false,
					MaxNumeric:    0,
					MaxNumericSet: false,
				}).Validate(string(params.IdempotencyKey)); err != nil {
					return errors.Wrap(err, "string")
				}
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return err
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "Idempotency-Key",
			In:   "header",
			Err:  err,
		}
	}
	return params, nil
}

// DeleteWorkspaceParams is parameters of deleteWorkspace operation.
type DeleteWorkspaceParams struct {
	IdempotencyKey string
	WorkspaceID    UUID
}

func unpackDeleteWorkspaceParams(packed middleware.Parameters) (params DeleteWorkspaceParams) {
	{
		key := middleware.ParameterKey{
			Name: "Idempotency-Key",
			In:   "header",
		}
		params.IdempotencyKey = packed[key].(string)
	}
	{
		key := middleware.ParameterKey{
			Name: "workspace_id",
			In:   "path",
		}
		params.WorkspaceID = packed[key].(UUID)
	}
	return params
}

func decodeDeleteWorkspaceParams(args [1]string, argsEscaped bool, r *http.Request) (params DeleteWorkspaceParams, _ error) {
	h := uri.NewHeaderDecoder(r.Header)
	// Decode header: Idempotency-Key.
	if err := func() error {
		cfg := uri.HeaderParameterDecodingConfig{
			Name:    "Idempotency-Key",
			Explode: false,
		}
		if err := h.HasParam(cfg); err == nil {
			if err := h.DecodeParam(cfg, func(d uri.Decoder) error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToString(val)
				if err != nil {
					return err
				}

				params.IdempotencyKey = c
				return nil
			}); err != nil {
				return err
			}
			if err := func() error {
				if err := (validate.String{
					MinLength:     16,
					MinLengthSet:  true,
					MaxLength:     128,
					MaxLengthSet:  true,
					Email:         false,
					Hostname:      false,
					Regex:         nil,
					MinNumeric:    0,
					MinNumericSet: false,
					MaxNumeric:    0,
					MaxNumericSet: false,
				}).Validate(string(params.IdempotencyKey)); err != nil {
					return errors.Wrap(err, "string")
				}
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return err
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "Idempotency-Key",
			In:   "header",
			Err:  err,
		}
	}
	// Decode path: workspace_id.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "workspace_id",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				var paramsDotWorkspaceIDVal uuid.UUID
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToUUID(val)
					if err != nil {
						return err
					}

					paramsDotWorkspaceIDVal = c
					return nil
				}(); err != nil {
					return err
				}
				params.WorkspaceID = UUID(paramsDotWorkspaceIDVal)
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "workspace_id",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// ForkWorkspaceParams is parameters of forkWorkspace operation.
type ForkWorkspaceParams struct {
	IdempotencyKey string
	WorkspaceID    UUID
}

func unpackForkWorkspaceParams(packed middleware.Parameters) (params ForkWorkspaceParams) {
	{
		key := middleware.ParameterKey{
			Name: "Idempotency-Key",
			In:   "header",
		}
		params.IdempotencyKey = packed[key].(string)
	}
	{
		key := middleware.ParameterKey{
			Name: "workspace_id",
			In:   "path",
		}
		params.WorkspaceID = packed[key].(UUID)
	}
	return params
}

func decodeForkWorkspaceParams(args [1]string, argsEscaped bool, r *http.Request) (params ForkWorkspaceParams, _ error) {
	h := uri.NewHeaderDecoder(r.Header)
	// Decode header: Idempotency-Key.
	if err := func() error {
		cfg := uri.HeaderParameterDecodingConfig{
			Name:    "Idempotency-Key",
			Explode: false,
		}
		if err := h.HasParam(cfg); err == nil {
			if err := h.DecodeParam(cfg, func(d uri.Decoder) error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToString(val)
				if err != nil {
					return err
				}

				params.IdempotencyKey = c
				return nil
			}); err != nil {
				return err
			}
			if err := func() error {
				if err := (validate.String{
					MinLength:     16,
					MinLengthSet:  true,
					MaxLength:     128,
					MaxLengthSet:  true,
					Email:         false,
					Hostname:      false,
					Regex:         nil,
					MinNumeric:    0,
					MinNumericSet: false,
					MaxNumeric:    0,
					MaxNumericSet: false,
				}).Validate(string(params.IdempotencyKey)); err != nil {
					return errors.Wrap(err, "string")
				}
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return err
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "Idempotency-Key",
			In:   "header",
			Err:  err,
		}
	}
	// Decode path: workspace_id.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "workspace_id",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				var paramsDotWorkspaceIDVal uuid.UUID
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToUUID(val)
					if err != nil {
						return err
					}

					paramsDotWorkspaceIDVal = c
					return nil
				}(); err != nil {
					return err
				}
				params.WorkspaceID = UUID(paramsDotWorkspaceIDVal)
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "workspace_id",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// GetComponentParams is parameters of getComponent operation.
type GetComponentParams struct {
	WorkspaceID UUID
	ComponentID UUID
}

func unpackGetComponentParams(packed middleware.Parameters) (params GetComponentParams) {
	{
		key := middleware.ParameterKey{
			Name: "workspace_id",
			In:   "path",
		}
		params.WorkspaceID = packed[key].(UUID)
	}
	{
		key := middleware.ParameterKey{
			Name: "component_id",
			In:   "path",
		}
		params.ComponentID = packed[key].(UUID)
	}
	return params
}

func decodeGetComponentParams(args [2]string, argsEscaped bool, r *http.Request) (params GetComponentParams, _ error) {
	// Decode path: workspace_id.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "workspace_id",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				var paramsDotWorkspaceIDVal uuid.UUID
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToUUID(val)
					if err != nil {
						return err
					}

					paramsDotWorkspaceIDVal = c
					return nil
				}(); err != nil {
					return err
				}
				params.WorkspaceID = UUID(paramsDotWorkspaceIDVal)
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "workspace_id",
			In:   "path",
			Err:  err,
		}
	}
	// Decode path: component_id.
	if err := func() error {
		param := args[1]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[1])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "component_id",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				var paramsDotComponentIDVal uuid.UUID
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToUUID(val)
					if err != nil {
						return err
					}

					paramsDotComponentIDVal = c
					return nil
				}(); err != nil {
					return err
				}
				params.ComponentID = UUID(paramsDotComponentIDVal)
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "component_id",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// GetGenerationParams is parameters of getGeneration operation.
type GetGenerationParams struct {
	WorkspaceID UUID
	Generation  int
}

func unpackGetGenerationParams(packed middleware.Parameters) (params GetGenerationParams) {
	{
		key := middleware.ParameterKey{
			Name: "workspace_id",
			In:   "path",
		}
		params.WorkspaceID = packed[key].(UUID)
	}
	{
		key := middleware.ParameterKey{
			Name: "generation",
			In:   "path",
		}
		params.Generation = packed[key].(int)
	}
	return params
}

func decodeGetGenerationParams(args [2]string, argsEscaped bool, r *http.Request) (params GetGenerationParams, _ error) {
	// Decode path: workspace_id.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "workspace_id",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				var paramsDotWorkspaceIDVal uuid.UUID
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToUUID(val)
					if err != nil {
						return err
					}

					paramsDotWorkspaceIDVal = c
					return nil
				}(); err != nil {
					return err
				}
				params.WorkspaceID = UUID(paramsDotWorkspaceIDVal)
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "workspace_id",
			In:   "path",
			Err:  err,
		}
	}
	// Decode path: generation.
	if err := func() error {
		param := args[1]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[1])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "generation",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToInt(val)
				if err != nil {
					return err
				}

				params.Generation = c
				return nil
			}(); err != nil {
				return err
			}
			if err := func() error {
				if err := (validate.Int{
					MinSet:        true,
					Min:           1,
					MaxSet:        false,
					Max:           0,
					MinExclusive:  false,
					MaxExclusive:  false,
					MultipleOfSet: false,
					MultipleOf:    0,
					Pattern:       nil,
				}).Validate(int64(params.Generation)); err != nil {
					return errors.Wrap(err, "int")
				}
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "generation",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// GetImportParams is parameters of getImport operation.
type GetImportParams struct {
	ImportID UUID
}

func unpackGetImportParams(packed middleware.Parameters) (params GetImportParams) {
	{
		key := middleware.ParameterKey{
			Name: "import_id",
			In:   "path",
		}
		params.ImportID = packed[key].(UUID)
	}
	return params
}

func decodeGetImportParams(args [1]string, argsEscaped bool, r *http.Request) (params GetImportParams, _ error) {
	// Decode path: import_id.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "import_id",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				var paramsDotImportIDVal uuid.UUID
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToUUID(val)
					if err != nil {
						return err
					}

					paramsDotImportIDVal = c
					return nil
				}(); err != nil {
					return err
				}
				params.ImportID = UUID(paramsDotImportIDVal)
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "import_id",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// GetMaterializationParams is parameters of getMaterialization operation.
type GetMaterializationParams struct {
	MaterializationID UUID
}

func unpackGetMaterializationParams(packed middleware.Parameters) (params GetMaterializationParams) {
	{
		key := middleware.ParameterKey{
			Name: "materialization_id",
			In:   "path",
		}
		params.MaterializationID = packed[key].(UUID)
	}
	return params
}

func decodeGetMaterializationParams(args [1]string, argsEscaped bool, r *http.Request) (params GetMaterializationParams, _ error) {
	// Decode path: materialization_id.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "materialization_id",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				var paramsDotMaterializationIDVal uuid.UUID
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToUUID(val)
					if err != nil {
						return err
					}

					paramsDotMaterializationIDVal = c
					return nil
				}(); err != nil {
					return err
				}
				params.MaterializationID = UUID(paramsDotMaterializationIDVal)
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "materialization_id",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// GetWorkspaceParams is parameters of getWorkspace operation.
type GetWorkspaceParams struct {
	WorkspaceID UUID
}

func unpackGetWorkspaceParams(packed middleware.Parameters) (params GetWorkspaceParams) {
	{
		key := middleware.ParameterKey{
			Name: "workspace_id",
			In:   "path",
		}
		params.WorkspaceID = packed[key].(UUID)
	}
	return params
}

func decodeGetWorkspaceParams(args [1]string, argsEscaped bool, r *http.Request) (params GetWorkspaceParams, _ error) {
	// Decode path: workspace_id.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "workspace_id",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				var paramsDotWorkspaceIDVal uuid.UUID
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToUUID(val)
					if err != nil {
						return err
					}

					paramsDotWorkspaceIDVal = c
					return nil
				}(); err != nil {
					return err
				}
				params.WorkspaceID = UUID(paramsDotWorkspaceIDVal)
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "workspace_id",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// ImportSourceParams is parameters of importSource operation.
type ImportSourceParams struct {
	IdempotencyKey string
	WorkspaceID    UUID
}

func unpackImportSourceParams(packed middleware.Parameters) (params ImportSourceParams) {
	{
		key := middleware.ParameterKey{
			Name: "Idempotency-Key",
			In:   "header",
		}
		params.IdempotencyKey = packed[key].(string)
	}
	{
		key := middleware.ParameterKey{
			Name: "workspace_id",
			In:   "path",
		}
		params.WorkspaceID = packed[key].(UUID)
	}
	return params
}

func decodeImportSourceParams(args [1]string, argsEscaped bool, r *http.Request) (params ImportSourceParams, _ error) {
	h := uri.NewHeaderDecoder(r.Header)
	// Decode header: Idempotency-Key.
	if err := func() error {
		cfg := uri.HeaderParameterDecodingConfig{
			Name:    "Idempotency-Key",
			Explode: false,
		}
		if err := h.HasParam(cfg); err == nil {
			if err := h.DecodeParam(cfg, func(d uri.Decoder) error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToString(val)
				if err != nil {
					return err
				}

				params.IdempotencyKey = c
				return nil
			}); err != nil {
				return err
			}
			if err := func() error {
				if err := (validate.String{
					MinLength:     16,
					MinLengthSet:  true,
					MaxLength:     128,
					MaxLengthSet:  true,
					Email:         false,
					Hostname:      false,
					Regex:         nil,
					MinNumeric:    0,
					MinNumericSet: false,
					MaxNumeric:    0,
					MaxNumericSet: false,
				}).Validate(string(params.IdempotencyKey)); err != nil {
					return errors.Wrap(err, "string")
				}
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return err
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "Idempotency-Key",
			In:   "header",
			Err:  err,
		}
	}
	// Decode path: workspace_id.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "workspace_id",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				var paramsDotWorkspaceIDVal uuid.UUID
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToUUID(val)
					if err != nil {
						return err
					}

					paramsDotWorkspaceIDVal = c
					return nil
				}(); err != nil {
					return err
				}
				params.WorkspaceID = UUID(paramsDotWorkspaceIDVal)
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "workspace_id",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// ListComponentsParams is parameters of listComponents operation.
type ListComponentsParams struct {
	Cursor      OptString `json:",omitempty,omitzero"`
	Limit       OptInt    `json:",omitempty,omitzero"`
	WorkspaceID UUID
}

func unpackListComponentsParams(packed middleware.Parameters) (params ListComponentsParams) {
	{
		key := middleware.ParameterKey{
			Name: "cursor",
			In:   "query",
		}
		if v, ok := packed[key]; ok {
			params.Cursor = v.(OptString)
		}
	}
	{
		key := middleware.ParameterKey{
			Name: "limit",
			In:   "query",
		}
		if v, ok := packed[key]; ok {
			params.Limit = v.(OptInt)
		}
	}
	{
		key := middleware.ParameterKey{
			Name: "workspace_id",
			In:   "path",
		}
		params.WorkspaceID = packed[key].(UUID)
	}
	return params
}

func decodeListComponentsParams(args [1]string, argsEscaped bool, r *http.Request) (params ListComponentsParams, _ error) {
	q := uri.NewQueryDecoder(r.URL.Query())
	// Decode query: cursor.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "cursor",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				var paramsDotCursorVal string
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToString(val)
					if err != nil {
						return err
					}

					paramsDotCursorVal = c
					return nil
				}(); err != nil {
					return err
				}
				params.Cursor.SetTo(paramsDotCursorVal)
				return nil
			}); err != nil {
				return err
			}
			if err := func() error {
				if value, ok := params.Cursor.Get(); ok {
					if err := func() error {
						if err := (validate.String{
							MinLength:     0,
							MinLengthSet:  false,
							MaxLength:     2048,
							MaxLengthSet:  true,
							Email:         false,
							Hostname:      false,
							Regex:         nil,
							MinNumeric:    0,
							MinNumericSet: false,
							MaxNumeric:    0,
							MaxNumericSet: false,
						}).Validate(string(value)); err != nil {
							return errors.Wrap(err, "string")
						}
						return nil
					}(); err != nil {
						return err
					}
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "cursor",
			In:   "query",
			Err:  err,
		}
	}
	// Set default value for query: limit.
	{
		val := int(100)
		params.Limit.SetTo(val)
	}
	// Decode query: limit.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "limit",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				var paramsDotLimitVal int
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToInt(val)
					if err != nil {
						return err
					}

					paramsDotLimitVal = c
					return nil
				}(); err != nil {
					return err
				}
				params.Limit.SetTo(paramsDotLimitVal)
				return nil
			}); err != nil {
				return err
			}
			if err := func() error {
				if value, ok := params.Limit.Get(); ok {
					if err := func() error {
						if err := (validate.Int{
							MinSet:        true,
							Min:           1,
							MaxSet:        true,
							Max:           500,
							MinExclusive:  false,
							MaxExclusive:  false,
							MultipleOfSet: false,
							MultipleOf:    0,
							Pattern:       nil,
						}).Validate(int64(value)); err != nil {
							return errors.Wrap(err, "int")
						}
						return nil
					}(); err != nil {
						return err
					}
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "limit",
			In:   "query",
			Err:  err,
		}
	}
	// Decode path: workspace_id.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "workspace_id",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				var paramsDotWorkspaceIDVal uuid.UUID
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToUUID(val)
					if err != nil {
						return err
					}

					paramsDotWorkspaceIDVal = c
					return nil
				}(); err != nil {
					return err
				}
				params.WorkspaceID = UUID(paramsDotWorkspaceIDVal)
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "workspace_id",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// ListGenerationsParams is parameters of listGenerations operation.
type ListGenerationsParams struct {
	Cursor      OptString `json:",omitempty,omitzero"`
	Limit       OptInt    `json:",omitempty,omitzero"`
	WorkspaceID UUID
}

func unpackListGenerationsParams(packed middleware.Parameters) (params ListGenerationsParams) {
	{
		key := middleware.ParameterKey{
			Name: "cursor",
			In:   "query",
		}
		if v, ok := packed[key]; ok {
			params.Cursor = v.(OptString)
		}
	}
	{
		key := middleware.ParameterKey{
			Name: "limit",
			In:   "query",
		}
		if v, ok := packed[key]; ok {
			params.Limit = v.(OptInt)
		}
	}
	{
		key := middleware.ParameterKey{
			Name: "workspace_id",
			In:   "path",
		}
		params.WorkspaceID = packed[key].(UUID)
	}
	return params
}

func decodeListGenerationsParams(args [1]string, argsEscaped bool, r *http.Request) (params ListGenerationsParams, _ error) {
	q := uri.NewQueryDecoder(r.URL.Query())
	// Decode query: cursor.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "cursor",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				var paramsDotCursorVal string
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToString(val)
					if err != nil {
						return err
					}

					paramsDotCursorVal = c
					return nil
				}(); err != nil {
					return err
				}
				params.Cursor.SetTo(paramsDotCursorVal)
				return nil
			}); err != nil {
				return err
			}
			if err := func() error {
				if value, ok := params.Cursor.Get(); ok {
					if err := func() error {
						if err := (validate.String{
							MinLength:     0,
							MinLengthSet:  false,
							MaxLength:     2048,
							MaxLengthSet:  true,
							Email:         false,
							Hostname:      false,
							Regex:         nil,
							MinNumeric:    0,
							MinNumericSet: false,
							MaxNumeric:    0,
							MaxNumericSet: false,
						}).Validate(string(value)); err != nil {
							return errors.Wrap(err, "string")
						}
						return nil
					}(); err != nil {
						return err
					}
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "cursor",
			In:   "query",
			Err:  err,
		}
	}
	// Set default value for query: limit.
	{
		val := int(100)
		params.Limit.SetTo(val)
	}
	// Decode query: limit.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "limit",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				var paramsDotLimitVal int
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToInt(val)
					if err != nil {
						return err
					}

					paramsDotLimitVal = c
					return nil
				}(); err != nil {
					return err
				}
				params.Limit.SetTo(paramsDotLimitVal)
				return nil
			}); err != nil {
				return err
			}
			if err := func() error {
				if value, ok := params.Limit.Get(); ok {
					if err := func() error {
						if err := (validate.Int{
							MinSet:        true,
							Min:           1,
							MaxSet:        true,
							Max:           500,
							MinExclusive:  false,
							MaxExclusive:  false,
							MultipleOfSet: false,
							MultipleOf:    0,
							Pattern:       nil,
						}).Validate(int64(value)); err != nil {
							return errors.Wrap(err, "int")
						}
						return nil
					}(); err != nil {
						return err
					}
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "limit",
			In:   "query",
			Err:  err,
		}
	}
	// Decode path: workspace_id.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "workspace_id",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				var paramsDotWorkspaceIDVal uuid.UUID
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToUUID(val)
					if err != nil {
						return err
					}

					paramsDotWorkspaceIDVal = c
					return nil
				}(); err != nil {
					return err
				}
				params.WorkspaceID = UUID(paramsDotWorkspaceIDVal)
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "workspace_id",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// ListPortableSnapshotsParams is parameters of listPortableSnapshots operation.
type ListPortableSnapshotsParams struct {
	WorkspaceID UUID
}

func unpackListPortableSnapshotsParams(packed middleware.Parameters) (params ListPortableSnapshotsParams) {
	{
		key := middleware.ParameterKey{
			Name: "workspace_id",
			In:   "path",
		}
		params.WorkspaceID = packed[key].(UUID)
	}
	return params
}

func decodeListPortableSnapshotsParams(args [1]string, argsEscaped bool, r *http.Request) (params ListPortableSnapshotsParams, _ error) {
	// Decode path: workspace_id.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "workspace_id",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				var paramsDotWorkspaceIDVal uuid.UUID
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToUUID(val)
					if err != nil {
						return err
					}

					paramsDotWorkspaceIDVal = c
					return nil
				}(); err != nil {
					return err
				}
				params.WorkspaceID = UUID(paramsDotWorkspaceIDVal)
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "workspace_id",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// ListWorkspacesParams is parameters of listWorkspaces operation.
type ListWorkspacesParams struct {
	Cursor OptString `json:",omitempty,omitzero"`
	Limit  OptInt    `json:",omitempty,omitzero"`
}

func unpackListWorkspacesParams(packed middleware.Parameters) (params ListWorkspacesParams) {
	{
		key := middleware.ParameterKey{
			Name: "cursor",
			In:   "query",
		}
		if v, ok := packed[key]; ok {
			params.Cursor = v.(OptString)
		}
	}
	{
		key := middleware.ParameterKey{
			Name: "limit",
			In:   "query",
		}
		if v, ok := packed[key]; ok {
			params.Limit = v.(OptInt)
		}
	}
	return params
}

func decodeListWorkspacesParams(args [0]string, argsEscaped bool, r *http.Request) (params ListWorkspacesParams, _ error) {
	q := uri.NewQueryDecoder(r.URL.Query())
	// Decode query: cursor.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "cursor",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				var paramsDotCursorVal string
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToString(val)
					if err != nil {
						return err
					}

					paramsDotCursorVal = c
					return nil
				}(); err != nil {
					return err
				}
				params.Cursor.SetTo(paramsDotCursorVal)
				return nil
			}); err != nil {
				return err
			}
			if err := func() error {
				if value, ok := params.Cursor.Get(); ok {
					if err := func() error {
						if err := (validate.String{
							MinLength:     0,
							MinLengthSet:  false,
							MaxLength:     2048,
							MaxLengthSet:  true,
							Email:         false,
							Hostname:      false,
							Regex:         nil,
							MinNumeric:    0,
							MinNumericSet: false,
							MaxNumeric:    0,
							MaxNumericSet: false,
						}).Validate(string(value)); err != nil {
							return errors.Wrap(err, "string")
						}
						return nil
					}(); err != nil {
						return err
					}
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "cursor",
			In:   "query",
			Err:  err,
		}
	}
	// Set default value for query: limit.
	{
		val := int(100)
		params.Limit.SetTo(val)
	}
	// Decode query: limit.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "limit",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				var paramsDotLimitVal int
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToInt(val)
					if err != nil {
						return err
					}

					paramsDotLimitVal = c
					return nil
				}(); err != nil {
					return err
				}
				params.Limit.SetTo(paramsDotLimitVal)
				return nil
			}); err != nil {
				return err
			}
			if err := func() error {
				if value, ok := params.Limit.Get(); ok {
					if err := func() error {
						if err := (validate.Int{
							MinSet:        true,
							Min:           1,
							MaxSet:        true,
							Max:           500,
							MinExclusive:  false,
							MaxExclusive:  false,
							MultipleOfSet: false,
							MultipleOf:    0,
							Pattern:       nil,
						}).Validate(int64(value)); err != nil {
							return errors.Wrap(err, "int")
						}
						return nil
					}(); err != nil {
						return err
					}
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "limit",
			In:   "query",
			Err:  err,
		}
	}
	return params, nil
}

// RefreshSourcesParams is parameters of refreshSources operation.
type RefreshSourcesParams struct {
	IdempotencyKey string
	WorkspaceID    UUID
}

func unpackRefreshSourcesParams(packed middleware.Parameters) (params RefreshSourcesParams) {
	{
		key := middleware.ParameterKey{
			Name: "Idempotency-Key",
			In:   "header",
		}
		params.IdempotencyKey = packed[key].(string)
	}
	{
		key := middleware.ParameterKey{
			Name: "workspace_id",
			In:   "path",
		}
		params.WorkspaceID = packed[key].(UUID)
	}
	return params
}

func decodeRefreshSourcesParams(args [1]string, argsEscaped bool, r *http.Request) (params RefreshSourcesParams, _ error) {
	h := uri.NewHeaderDecoder(r.Header)
	// Decode header: Idempotency-Key.
	if err := func() error {
		cfg := uri.HeaderParameterDecodingConfig{
			Name:    "Idempotency-Key",
			Explode: false,
		}
		if err := h.HasParam(cfg); err == nil {
			if err := h.DecodeParam(cfg, func(d uri.Decoder) error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToString(val)
				if err != nil {
					return err
				}

				params.IdempotencyKey = c
				return nil
			}); err != nil {
				return err
			}
			if err := func() error {
				if err := (validate.String{
					MinLength:     16,
					MinLengthSet:  true,
					MaxLength:     128,
					MaxLengthSet:  true,
					Email:         false,
					Hostname:      false,
					Regex:         nil,
					MinNumeric:    0,
					MinNumericSet: false,
					MaxNumeric:    0,
					MaxNumericSet: false,
				}).Validate(string(params.IdempotencyKey)); err != nil {
					return errors.Wrap(err, "string")
				}
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return err
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "Idempotency-Key",
			In:   "header",
			Err:  err,
		}
	}
	// Decode path: workspace_id.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "workspace_id",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				var paramsDotWorkspaceIDVal uuid.UUID
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToUUID(val)
					if err != nil {
						return err
					}

					paramsDotWorkspaceIDVal = c
					return nil
				}(); err != nil {
					return err
				}
				params.WorkspaceID = UUID(paramsDotWorkspaceIDVal)
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "workspace_id",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// ReleaseMaterializationParams is parameters of releaseMaterialization operation.
type ReleaseMaterializationParams struct {
	IdempotencyKey    string
	MaterializationID UUID
}

func unpackReleaseMaterializationParams(packed middleware.Parameters) (params ReleaseMaterializationParams) {
	{
		key := middleware.ParameterKey{
			Name: "Idempotency-Key",
			In:   "header",
		}
		params.IdempotencyKey = packed[key].(string)
	}
	{
		key := middleware.ParameterKey{
			Name: "materialization_id",
			In:   "path",
		}
		params.MaterializationID = packed[key].(UUID)
	}
	return params
}

func decodeReleaseMaterializationParams(args [1]string, argsEscaped bool, r *http.Request) (params ReleaseMaterializationParams, _ error) {
	h := uri.NewHeaderDecoder(r.Header)
	// Decode header: Idempotency-Key.
	if err := func() error {
		cfg := uri.HeaderParameterDecodingConfig{
			Name:    "Idempotency-Key",
			Explode: false,
		}
		if err := h.HasParam(cfg); err == nil {
			if err := h.DecodeParam(cfg, func(d uri.Decoder) error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToString(val)
				if err != nil {
					return err
				}

				params.IdempotencyKey = c
				return nil
			}); err != nil {
				return err
			}
			if err := func() error {
				if err := (validate.String{
					MinLength:     16,
					MinLengthSet:  true,
					MaxLength:     128,
					MaxLengthSet:  true,
					Email:         false,
					Hostname:      false,
					Regex:         nil,
					MinNumeric:    0,
					MinNumericSet: false,
					MaxNumeric:    0,
					MaxNumericSet: false,
				}).Validate(string(params.IdempotencyKey)); err != nil {
					return errors.Wrap(err, "string")
				}
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return err
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "Idempotency-Key",
			In:   "header",
			Err:  err,
		}
	}
	// Decode path: materialization_id.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "materialization_id",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				var paramsDotMaterializationIDVal uuid.UUID
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToUUID(val)
					if err != nil {
						return err
					}

					paramsDotMaterializationIDVal = c
					return nil
				}(); err != nil {
					return err
				}
				params.MaterializationID = UUID(paramsDotMaterializationIDVal)
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "materialization_id",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// RestoreWorkspaceParams is parameters of restoreWorkspace operation.
type RestoreWorkspaceParams struct {
	IdempotencyKey string
	WorkspaceID    UUID
}

func unpackRestoreWorkspaceParams(packed middleware.Parameters) (params RestoreWorkspaceParams) {
	{
		key := middleware.ParameterKey{
			Name: "Idempotency-Key",
			In:   "header",
		}
		params.IdempotencyKey = packed[key].(string)
	}
	{
		key := middleware.ParameterKey{
			Name: "workspace_id",
			In:   "path",
		}
		params.WorkspaceID = packed[key].(UUID)
	}
	return params
}

func decodeRestoreWorkspaceParams(args [1]string, argsEscaped bool, r *http.Request) (params RestoreWorkspaceParams, _ error) {
	h := uri.NewHeaderDecoder(r.Header)
	// Decode header: Idempotency-Key.
	if err := func() error {
		cfg := uri.HeaderParameterDecodingConfig{
			Name:    "Idempotency-Key",
			Explode: false,
		}
		if err := h.HasParam(cfg); err == nil {
			if err := h.DecodeParam(cfg, func(d uri.Decoder) error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToString(val)
				if err != nil {
					return err
				}

				params.IdempotencyKey = c
				return nil
			}); err != nil {
				return err
			}
			if err := func() error {
				if err := (validate.String{
					MinLength:     16,
					MinLengthSet:  true,
					MaxLength:     128,
					MaxLengthSet:  true,
					Email:         false,
					Hostname:      false,
					Regex:         nil,
					MinNumeric:    0,
					MinNumericSet: false,
					MaxNumeric:    0,
					MaxNumericSet: false,
				}).Validate(string(params.IdempotencyKey)); err != nil {
					return errors.Wrap(err, "string")
				}
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return err
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "Idempotency-Key",
			In:   "header",
			Err:  err,
		}
	}
	// Decode path: workspace_id.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "workspace_id",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				var paramsDotWorkspaceIDVal uuid.UUID
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToUUID(val)
					if err != nil {
						return err
					}

					paramsDotWorkspaceIDVal = c
					return nil
				}(); err != nil {
					return err
				}
				params.WorkspaceID = UUID(paramsDotWorkspaceIDVal)
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "workspace_id",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// StreamWorkspaceEventsParams is parameters of streamWorkspaceEvents operation.
type StreamWorkspaceEventsParams struct {
	LastEventID OptString `json:",omitempty,omitzero"`
	WorkspaceID UUID
}

func unpackStreamWorkspaceEventsParams(packed middleware.Parameters) (params StreamWorkspaceEventsParams) {
	{
		key := middleware.ParameterKey{
			Name: "Last-Event-ID",
			In:   "header",
		}
		if v, ok := packed[key]; ok {
			params.LastEventID = v.(OptString)
		}
	}
	{
		key := middleware.ParameterKey{
			Name: "workspace_id",
			In:   "path",
		}
		params.WorkspaceID = packed[key].(UUID)
	}
	return params
}

func decodeStreamWorkspaceEventsParams(args [1]string, argsEscaped bool, r *http.Request) (params StreamWorkspaceEventsParams, _ error) {
	h := uri.NewHeaderDecoder(r.Header)
	// Decode header: Last-Event-ID.
	if err := func() error {
		cfg := uri.HeaderParameterDecodingConfig{
			Name:    "Last-Event-ID",
			Explode: false,
		}
		if err := h.HasParam(cfg); err == nil {
			if err := h.DecodeParam(cfg, func(d uri.Decoder) error {
				var paramsDotLastEventIDVal string
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToString(val)
					if err != nil {
						return err
					}

					paramsDotLastEventIDVal = c
					return nil
				}(); err != nil {
					return err
				}
				params.LastEventID.SetTo(paramsDotLastEventIDVal)
				return nil
			}); err != nil {
				return err
			}
			if err := func() error {
				if value, ok := params.LastEventID.Get(); ok {
					if err := func() error {
						if err := (validate.String{
							MinLength:     0,
							MinLengthSet:  false,
							MaxLength:     128,
							MaxLengthSet:  true,
							Email:         false,
							Hostname:      false,
							Regex:         nil,
							MinNumeric:    0,
							MinNumericSet: false,
							MaxNumeric:    0,
							MaxNumericSet: false,
						}).Validate(string(value)); err != nil {
							return errors.Wrap(err, "string")
						}
						return nil
					}(); err != nil {
						return err
					}
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "Last-Event-ID",
			In:   "header",
			Err:  err,
		}
	}
	// Decode path: workspace_id.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "workspace_id",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				var paramsDotWorkspaceIDVal uuid.UUID
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToUUID(val)
					if err != nil {
						return err
					}

					paramsDotWorkspaceIDVal = c
					return nil
				}(); err != nil {
					return err
				}
				params.WorkspaceID = UUID(paramsDotWorkspaceIDVal)
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "workspace_id",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}
